### ISSUE TITLE
[bug] Initially selected screenshot not loading.

### ISSUE THREAD

**Issue by 1Michael23** [NeoApplications/Neo-Store#104]
Upon tapping on a screenshot, that screenshot will not load, the background will fade and become full screen as if an image was there, but nothing loads. 

Swiping to a new screenshot will load it successfully, swiping back will not load the initial screenshot.

This isnt a major bug because any app with more than one screenshot can still have them viewed with a couple of extra taps.

**Comment by avently** [comment]
This behavior started to happen some a few versions ago. Is it hard to fix?

**Comment by Offerel** [comment]
Is there any timeline to fix that?

**Comment by machiav3lli** [comment]
It seems to be a problem on Coil's side of things. Caching seems not that reliable. We'll see into it later when we finish the re-writing
