### ISSUE TITLE
[FR] Backup/restore list of installed apps

### ISSUE THREAD

**Issue by yephny** [NeoApplications/Neo-Store#106]
**Is your feature request related to a problem? Please describe.**
After a factory reset, all I can do to get my apps back is to either install them manually one by one or use an app like OAndBackupX to have apk backups, resulting in unnecessarily high space usage.

**Describe the solution you'd like**
[As requested in this reddit post](https://www.reddit.com/r/fdroid/comments/cgweim/how_to_backup_list_of_f_droid_apps/), I too prefer having an app to take a backup of the list of apps installed from F-Droid, which is a task well-suited for Droid-ify.

**Comment by Iamlooker** [comment]
This could be done only after we complete our migrate to room database.

I also want this feature too ease my life too

🥲

**Comment by maverick74** [comment]
I want this too!

**Comment by maverick74** [comment]
Let me add that being able to backup the favourite's list would also be great :)

**Comment by KaKi87** [comment]
Hello @machiav3lli & @Iamlooker, any news on this ? Thanks

**Comment by Iamlooker** [comment]
> Hello @machiav3lli & @Iamlooker, any news on this ? Thanks

I am not involved in the project anymore. I am handling Droid-ify again.

**Comment by machiav3lli** [comment]
Added in 666a939

**Comment by KaKi87** [comment]
Hi,
I see the commit is 3 weeks old and the major version containing has been in alpha for 5 months.
Will it be released anytime soon ?
Thanks

**Comment by machiav3lli** [comment]
Soon is relative… but I guess there'll be couple of test releases till stable

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks
