### ISSUE TITLE
Trackers & loggers report

### ISSUE THREAD

**Issue by Donkey-Doug** [NeoApplications/Neo-Store#11]
Exodus is a tool to find trackers and loggers in apps. Please add exodus reports to the apps in droid-ify.

Aurora Store has these reports built in and there is an app on fdroid (izzydroid repo) called "warden" which retrieves exodus reports (link: https://apt.izzysoft.de/fdroid/index/apk/com.aurora.warden)

Exodus website: https://reports.exodus-privacy.eu.org/en/

---
**Examples**
Exodus website:
![Screenshot_20211006-235408_Firefox](https://user-images.githubusercontent.com/50382414/136288908-4d062d79-c7ab-4619-84d0-dfc6daaa8aec.png)

Aurora store:
![Screenshot_20211006-234909_Aurora_Store](https://user-images.githubusercontent.com/50382414/136288292-a8308cd4-2725-40c0-b28d-3967bd692b4d.png)

Warden (report from firefox):
![Screenshot_20211006-234437_Warden](https://user-images.githubusercontent.com/50382414/136288191-af6b0d6b-a3b5-4b50-8e0c-770227681f8b.png)

![Screenshot_20211006-234441_Warden](https://user-images.githubusercontent.com/50382414/136288216-1e4315e9-c3dd-49db-b8ac-4cef940c7c42.png)

**Comment by machiav3lli** [comment]
This is also already on my todo list

**Comment by machiav3lli** [comment]
Done since 0.9.11
