### ISSUE TITLE
Change the name of the app

### ISSUE THREAD

**Issue by yephny** [NeoApplications/Neo-Store#113]
**Is your feature request related to a problem? Please describe.**
As an example, the name Foxy Droid has some character, it's Foxy. In search-based launchers, you can simply type Foxy and launch the app. Droid-ify, on the other hand, has no character: Droid is Android, many apps have this in their name and -ify doesn't even mean anything.

**Describe the solution you'd like**
I think the app should be renamed to something that is original and has character. Newpipe's fork that has SponsorBlock implementation, for instance, is looking to change its name. That's what I'm talking about.

A name change would make the app memorable, allowing anyone to easily find it.

**Comment by Donkey-Doug** [comment]
To what?

Do you have a suggestion?

**Comment by Iamlooker** [comment]
Droid-ify -> Droidify  ?

**Comment by machiav3lli** [comment]
@Iamlooker 😆

**Comment by yephny** [comment]
I can come up with several names but I think @Iamlooker as the rightful owner of the repo should do it. Whatever I come up with, it won't fit to the app as it's a personal thing more than anything.

OctoDroid, Foxy Droid, Pulse Music, Fennec, Frost, Imagepipe, Scrambled Exif, Infinity, Slide, Newpipe, Syphon, Binary Eye are some of the good examples you can find on F-Droid. 

Just get creative, it could literally be anything. Lion Droid? Easy. Current? Simple. Triplet? Quirky.

**Comment by Donkey-Doug** [comment]
open store

foss store
fosstore

software hub

android store
droid store

**Comment by 0rdinant** [comment]
ReDroid is a good name I think. Only problem is that the name's [taken](https://github.com/yzygitzh/ReDroid), although that program is unmaintained. ReDroid is snappy and doesn't depart from the "Droid" identity so the logo could stay.

**Comment by yephny** [comment]
Since the app (at least the repository, for now) is now named Neo-Store, this issue can be closed, right?
