### ISSUE TITLE
Redesign Navigation

### ISSUE THREAD

**Issue by comradekingu** [NeoApplications/Neo-Store#117]
Right now there are three categories.
`
Available | Installed | Updates`

They list, respectively
all installable apps,
all installed apps,
upgradable apps.

The latter caregory is empty if all installed apps are up to date.

Instead of a category of its own, upgradable apps could be sorted to the top of "Installed".
Thus making it
`Available | Installed`

Benefits:

No empty category for new users (whom will all install only fresh apps).
Visual space is saved
Less entropy on screen
Easier to fit the entire translation in languages that have long words/on smaller screens.
No confusion between "update/upgrade" (the repo list is updated, and apps are upgraded)
There will be a way to get to all categories with one swipe. (Right now "Available" to "Updates" and vice-versa is not possible.)

**Comment by Donkey-Doug** [comment]
Or only show the updates section when there are updates available.

**Comment by yephny** [comment]
I don't agree with this at all. Why do I have to see a list of updates when I just want to browse my installed apps? The way 3-swipe UI works right now makes everything quite clear.

**Comment by comradekingu** [comment]
@Donkey-Doug That is a focus-shifting and non-consistent UI. As mentioned it just wastes space most of the time.

@yephny As detailed in the first post, if you want to swipe from one thing to the other, three categories makes it all less accessible since one category is always inaccessible unless you are in the middle.
It also makes it inconsistent, because with three categories a swipe in either direction doesn't go to the same category all the time. 

On the topic of browsing ones apps, I should think nothing is more important in a package-manager than installed apps requiring upgrades? No part of what or how you browse in "Installed" is taken away by seeing upgrades for the few apps that have them.
There are otherwise better tools for browsing apps available without opening an app.

**Comment by Iamlooker** [comment]
@comradekingu We are planning to move to bottom navigation.

Your point does make a lotta sense

**Comment by comradekingu** [comment]
@Iamlooker That makes even more sense from an ergonomic point of view. :)

**Comment by machiav3lli** [comment]
Both @comradekingu and @yephny  points make some sense. As @Iamlooker mentioned, we're planning a change to bottom navigation and am considering three tabs/pages:

`Available/Apps | Categories | Installed&Updates`

With those we have a clear separation of considerations with enough logic in each.

**Comment by Donkey-Doug** [comment]
Not a fan of the categories tab. I would never use it. 

Why are installed and updates merged? 4 tabs is not too much. Google recommends 3, 4 or 5 tabs anyway. They could be seperated.

> Bottom navigation bars display three to five destinations at the bottom of a screen. Each destination is represented by an icon and an optional text label. When a bottom navigation icon is tapped, the user is taken to the top-level navigation destination associated with that icon. Bottom navigation shouldn’t be used for user preferences or settings.

**Comment by yephny** [comment]
@comradekingu I believe you are assuming how other people use the app. You might have "only a few" apps that have an update available, but some people never update their apps unless there are changes made in an update that make it worthwhile, thus leading to a comparably long list of updates.

On topic of browsing installed apps, I don't think there is a better tool than this app when I want to see only the apps installed from F-Droid.

**Comment by yephny** [comment]
I wholeheartedly agree with everything @Donkey-Doug is suggesting about this issue.

**Comment by comradekingu** [comment]
@yephny Is that to save bandwidth?

Inherent to that argument, why would those people upgrade Droid-ify?
There is "F-Droid Classic" and "Foxy Droid" serving such a market.
As different from what even F-Droid does, less complexity I should think is good motivation.

If you are making the conscious decision to read through changelogs to find out whether there are security concerns,
whether to upgrade or not is really an even greater concern, suggesting it is more urgent.
From there one can elect to "ignore this version" for whatever reason.
So what I am saying is I don't see a (good) use-case for just leaving upgradable apps uninstalled.

Upgradable apps are not different from installed ones, but rather a quality thereof.
This is further divided from the dichotomy of "available" to "installed"
When you install Droid-ify there (often) won't be anything to upgrade, and that has always been hard to explain to new users.
It is an empty unanswered category that doesn't explain itself very well.
In the very least it is more complex.

Personally I'd like just one tab (for phone type screens):

---
Current  "︙"
Floating "(﹀)" (like F-Droid search) to bring up the current selection dropdown

~Upgrades (if available)
~Available
~Installed

[Type to search…]

---

- Pull ↓ from top position to fetch update lists ↻
- Swipe ← to go to (upgrades+)Available
- Swipe → to go to Installed

New upgrades prominent right away when opening the app.

Saves one line of vertical space.

Swipes always go to one view

Less UI interference since "Available/Apps | Categories | Installed&Updates" is gone.
The main UI appears localized to everyone because it doesn't have any text.

Searching takes one less click (because it is an input field rather than a button).
Searches save swipes because there is no need to select tab first.
Search results over multiple categories are available without navigation if narrowed down enough.

Advanced search and configuration is possible, but those are the basics.

**Option 2**:

---

Floating "(﹀)" (like F-Droid search) to bring up the current selection dropdown

~Upgrades (if available)
~Available
~Installed
~**Settings**
~**Repos**

[Type to search…]

---

- Pull ↓ from top position to fetch update lists ↻
- Swipe → to go to next section
- Swipe ← to go to previous section

Swipes don't always go to the same view, but the same functionality covers more functions.

All functionality is available in the same view

Search can now find Settings 
Search can now find Repos
Clicks and navigation saved to turn a repo on if a search doesn't find an app in a similarly named repo.

Less UI interference because there is no "︙ " button

**Comment by Donkey-Doug** [comment]
I wanted to share this image of the gnome software center. Obviously it is for larger screens, but the layout is still very nice and the UI is adaptive to phones:

![app-page-adaptive](https://user-images.githubusercontent.com/50382414/143767235-277fe364-8eef-4249-b3cf-dce8f56d072d.png)

**Comment by Donkey-Doug** [comment]
I would suggest 3 tabs:

- Explore
- Installed
- Updates

The installed ans updates tab can be very simple. The explore tab should have an option for sorting and filtering. Possible filters can be:

- Categories (games, music, maps etc.)
- Repo (fdroid, izzydroid etc.)
