### ISSUE TITLE
About the green tint in dark/AMOLED themes

### ISSUE THREAD

**Issue by OliverLew** [NeoApplications/Neo-Store#123]
Current there is green tint in
- Author button
- Install//Details/Update button (different functionality depends on which tab it is)
- The three-dot collapsed menu
- Edit: I think even the placeholder icon has green tint

I am not familiar with material design, so not sure if the green tint is a good design. For me personally, I'd be more comfortable if they be using primary colors (gray in this case), maybe with different shades/tones.

Edit2: I noticed in light theme, the whole app uses greenish primary colors, so the green tint fits quite well (the green is still too light to me, tho). But in the dark theme, the primary colors are grays, maybe a brighter gray is better.

![IMG_20211118_133425](https://user-images.githubusercontent.com/12032219/142359022-8565f12e-ccb4-4e48-9d70-8278048bad45.jpg)
![IMG_20211118_133450](https://user-images.githubusercontent.com/12032219/142359027-087d0236-9dcb-4267-bcbe-a2469fd2e1e5.jpg)

**Comment by Mokura** [comment]
I'd also like the ability to choose your own accent color, as long as it's not too far outside the design spec for the app.

**Comment by Iamlooker** [comment]
Greying them will make them similiar to other grey things and this will lead to different attention spans.

So it would be a bad idea

**Comment by Iamlooker** [comment]
But about that profile pic card which has a different tint, I will maybe fix it....MAYBE....

**Comment by OliverLew** [comment]
I only pointed them out based on my observations in other apps. Something I feel odd:
- The greenish gray doesn't has enough contrast with actual gray colors. From my own preference and [reading some references](https://material.io/design/color/the-color-system.html#color-usage-and-palettes), colors in one palette (primary or secondary) should be similar, but distinctive other wise. So what I am imagining is, use lighter gray (as another primary color) or a more vibrant green (as a secondary color).
- For the 3-dot menu, I find it weird to have the menu of non-neutral color with neutral primary colors (gray). I look through all material design apps on my phone, and none of them has that color combination.

Not sure if these make sense ...

**Comment by OliverLew** [comment]
Trying the latest NeoStore beta, I think this issue is invalid now.
