### ISSUE TITLE
Source code link

### ISSUE THREAD

**Issue by VishnuSanal** [NeoApplications/Neo-Store#127]
Now, we have to open change log or bug tracker first & then open source code from there. The native F-Droid client have a direct link to the source code. I think a similar field would be great addition Droid-ify.

@Iamlooker What do you think? If you think this can be added to Droid-ify, I'd like to work on it.

**Comment by Iamlooker** [comment]
Actually if you click on the profile picture it will take you to the source code.

**Right Most Card**

![Screenshot_20211125-130956_Droid-ify-Debug](https://user-images.githubusercontent.com/60404093/143399619-6ea52d13-f283-44fa-9089-8727bb13c1f1.png)

**Comment by VishnuSanal** [comment]
> Actually if you click on the profile picture it will take you to the source code.
> 
> **Right Most Card**

Oh, okay, haven't noticed it. Thanks!

Anyways, I think a user (myself included) would expect it to go to the developer's profile & not the source code. It can be more intuitive. IMO. What say?

> ![Screenshot_20211125-130956_Droid-ify-Debug](https://user-images.githubusercontent.com/60404093/143399619-6ea52d13-f283-44fa-9089-8727bb13c1f1.png)

PS: Thanks for finding my app! XD

**Comment by Iamlooker** [comment]
> 
> :O You found my app! XD

How could I not notice such a highly updated apps on the feed XD

**Comment by VishnuSanal** [comment]
> Anyways, I think a user (myself included) would expect it to go to the developer's profile & not the source code. It can be more intuitive, IMO. What say?

I think you missed this...

**Comment by Iamlooker** [comment]
> > Anyways, I think a user (myself included) would expect it to go to the developer's profile & not the source code. It can be more intuitive, IMO. What say?
> 
> I think you missed this...

XD

No no I was just thinking about a workaround.

Would be useless to give hope If I am unable to fix it but I think I have something in mind.

Maybe will notify today itself

**Comment by VishnuSanal** [comment]
> No no I was just thinking about a workaround.

One thing I thought of was adding one more item (source code) to the links section & pointing the profile card to the developer account or to remove the link on the card altogether.

> If I am unable to fix it

I was giving suggestions & it's you who should decide whether to change the current layout or not! Anyways, thanks for the concern.

**Comment by machiav3lli** [comment]
@Iamlooker I agree with @VishnuSanal  and think we can do separate buttons for author and repo using different layouts.

**Comment by Iamlooker** [comment]
I do agree with him too.
Just thinking how to implement in a different way

**Comment by shuvashish76** [comment]
Suggestions:

- Droid-ify should add source code link to the "Links" section just like F-Droid official app.
![Screenshot_2021-11-25-15-35-49](https://user-images.githubusercontent.com/48226312/143421397-892998fb-24c1-40e7-ad19-3d298da6e423.jpeg)

> user would expect it to go to the developer's profile
- I disagree with @VishnuSanal ; developer's profile link seems unnecessary to me.
Clicking on author should show all apps created by the same matching author (from all enabled repos) just like Playstore.

For ex:
https://play.google.com/store/apps/dev?id=5733306165707047154
![Screenshot_2021-11-25-15-02-35](https://user-images.githubusercontent.com/48226312/143422655-a66092bc-b5fb-44d6-818d-5ac997f15b9a.jpeg)
(_screenshot from Aurora Store_)

That way it should show both [Quotes](https://github.com/VishnuSanal/Quotes) & [DMP](https://github.com/VishnuSanal/DialogMusicPlayer) app if user click on @VishnuSanal 's name.

- G-Droid app has this author feature (but clicking on the author name from any app doesn't work though)
![Screenshot_2021-11-25-15-25-40](https://user-images.githubusercontent.com/48226312/143423756-a302a530-43dd-47cd-a554-f9f49d66f8e5.jpeg)
![Screenshot_2021-11-25-15-26-52](https://user-images.githubusercontent.com/48226312/143423816-a6249aa6-61cd-4119-bcb0-4ae63d898b7b.jpeg)
![Screenshot_2021-11-25-15-27-03](https://user-images.githubusercontent.com/48226312/143423861-3ea2d3ee-56c0-4197-8257-86616f295687.jpeg)

Thankyou🙏🏿

**Comment by shuvashish76** [comment]
@Iamlooker any updates?

**Comment by saulhdev** [comment]
The source code link is already implemented on v. 0.9.1

**Comment by saulhdev** [comment]
The source code link is already implemented on v0.9.1
