### ISSUE TITLE
[Feature request] Tab Download

### ISSUE THREAD

**Issue by Pantyhose-X** [NeoApplications/Neo-Store#149]
add Tab Download In progress
I downloaded multiple apps at the same time and had to search and click install again and again

**Comment by Pranab009** [comment]
When neo store is available at Fdroid

**Comment by rusty-snake** [comment]
https://f-droid.org/packages/com.machiav3lli.fdroid/
https://android.izzysoft.de/repo/apk/com.machiav3lli.fdroid
