### ISSUE TITLE
Date format localization

### ISSUE THREAD

**Issue by Donkey-Doug** [NeoApplications/Neo-Store#151]
Make it possible to use DD/MM/YY instead of MM/DD/YY. Preferably, use the phone default format.

**Comment by machiav3lli** [comment]
We're already using system's default. You sure you are not using the wrong system locale or mis-interprete the chosen local's date format?

**Comment by Donkey-Doug** [comment]
![Screenshot_20211219-202211_Settings](https://user-images.githubusercontent.com/50382414/146687969-e6dc18b9-55a3-44ee-99eb-596f1f30b47a.png)

Dutch region, but I have MM/DD/YY instead of DD/MM/YY.

**Comment by machiav3lli** [comment]
I use the German locale and get DD.MM.YYYY just fine and just tested using the Dutch locale in the app and it provides DD-MM-YYYY format. So if you could point me out to where this mis-formatted date is, I can fix if there's anything to be fixed.

**Comment by Donkey-Doug** [comment]
![Screenshot_20211220-132017_Droid-ify](https://user-images.githubusercontent.com/50382414/146766330-55b1f1ca-2436-4e92-93f0-a1b94d69c21e.png)

**Comment by Donkey-Doug** [comment]
Android 10
LineageOS without google play services.

**Comment by Donkey-Doug** [comment]
To be honest, it could be my custom rom. If I select automatic time format it changes to AM/PM.

**Comment by Donkey-Doug** [comment]
Closing, because I think it is my custom ROM.

**Comment by haarp** [comment]
I'm seeing the same problem on LineageOS. I don't think it's the ROM. Could you reopen, @Donkey-Doug ?

It seems Droidify uses the language to determine the date format, instead of using the region. Thus any English locale will result in MM/DD/YYYY.

**Comment by Donkey-Doug** [comment]
I use english language on my phone with dutch timezone. Using the language to determine date format is wrong. Only droid-ify does this. All other apps have the correct date format.

**Comment by samyak039** [comment]
the issue is there, I use English(India) and we have DD/MM/YY format but getting MM/DD/YY
