### ISSUE TITLE
[SUGGESTION] Metadata locale

### ISSUE THREAD

**Issue by billthefarmer** [NeoApplications/Neo-Store#166]
I am told, untested, that your app does not work with my [apps](https://duckduckgo.com/?t=ffab&q=site%3A+f-droid.org+billthefarmer&ia=web), which use the `en_GB` locale for the metadata as I am not a [leftpondian](https://en.wiktionary.org/wiki/Leftpondian) and it works with F-DROID and [IzzyOnDroid](https://android.izzysoft.de/repo). So I did a search on your code and found, in [IndexV1Parser.kt](https://github.com/Iamlooker/Droid-ify/blob/master/src/main/kotlin/com/looker/droidify/index/IndexV1Parser.kt), where you try `en-US`, `en_US`, and `en`:
```kotlin
    private fun <T> Map<String, Localized>.find(callback: (String, Localized) -> T?): T? {
        return getAndCall("en-US", callback) ?: getAndCall("en_US", callback) ?: getAndCall(
            "en",
            callback
        )
    }
```
There are quite a few `en_*` locales, would it not be better to do some sort of wildcard regex style match? I don't understand your kotlin code, so I couldn't offer a pull request.

**Comment by Iamlooker** [comment]
Thanks for your hard work on doing so much research for our help.

We will definitely look into this in next update

**Comment by xuangeyouneihan** [comment]
#66
