### ISSUE TITLE
Add Cloudflare to list of supported F-Droid mirrors

### ISSUE THREAD

**Issue by mariobrostech** [NeoApplications/Neo-Store#170]
Hi,

Is there any way that Cloudflare can be added to the list of supported F-Droid mirrors when tapping on the arrow next to the F-Droid repository URL?

Here's the direct link to the repo:
[https://cloudflare.f-droid.org/repo?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB](https://cloudflare.f-droid.org/repo?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB)

Thanks in advance!

**Comment by mahdi1234** [comment]
Perhaps similar to https://github.com/Iamlooker/Droid-ify/issues/163 ?

**Comment by mariobrostech** [comment]
It is, but I opened this issue because I saw that mirrors were already an implemented feature for the F-Droid repo.

**Comment by mahdi1234** [comment]
Ahh you're right, didn't notice. But you can only select one and it fetches everything whereas official app alternates. Got it - in your case adding custom url would solve it.

**Comment by mariobrostech** [comment]
Yeah, changing the URL solves it, but I agree that the feature could be a bit more intuitive (a dropdown arrow is small and hard to notice, and I didn't realize it was there right away), and it should also be able to support multiple mirrors, like the official app.

**Comment by Iamlooker** [comment]
So what fo you think the implementation should be like?

As far as I understood from this conversation,

We should simplely give option to add more repos and allow them to be easier to select?

But according to #163 we should periodically test the performance of each repo and select the most performamt


First one seem like a feasible feature to implement but usability will not be improve vastly. You will need to check performance on your own.

And second doesnt seem that feasible to me atleast (I would like some suggestions @machiav3lli )

I will look into what Official F-Droid actually implemented.

Of I am wrong about this interpretation kindly correct me.

**Comment by mahdi1234** [comment]
What I think is easy to answer:

- the app should come up with list of all official f-droid mirrors
- mirrors should be user selectable (one or multiple)
- app should somehow alternate those mirrors

What I have no answer to:

- should all be enabled by default - probably not (Europe vs Asia makes huge difference)
- which should be enabled by default and how to decide

I don't think app should periodically check performance ... but maybe could have a on demand "test" option.

**Comment by yephny** [comment]
For those who wish not to use the Cloudflare mirror (there are plenty), it shouldn't be enforced based on mirror performance.

**Comment by proletarius101** [comment]
> should all be enabled by default - probably not (Europe vs Asia makes huge difference)

I think we can easily make it disabled by default only within EU since that's controversial. For other places, enabled by default obviously gives more benefits over disadvantages.

And anyone can change the settings for themselves.

**Comment by machiav3lli** [comment]
Should be fixed on 1.0.0. Using auto-rotation on mirrors is an another issue #163
