### ISSUE TITLE
Anti-feature filter

### ISSUE THREAD

**Issue by jcperil** [NeoApplications/Neo-Store#179]
Add an option in Settings to customize how we want to filter apps based on anti-features. Picture attached from F-Droid UI.

![anti feature filter](https://user-images.githubusercontent.com/89805719/154907532-642cb609-3944-4f36-a1c2-ce25f87a3d5f.jpg)

**Comment by Donkey-Doug** [comment]
Related: https://github.com/Iamlooker/Droid-ify/issues/11

**Comment by machiav3lli** [comment]
Added in 1.0.0
