### ISSUE TITLE
KiwiBrowser GitHub version 

### ISSUE THREAD

**Issue by mmtech2012** [NeoApplications/Neo-Store#184]
Hi
Would you configure Droid-ify to detect GitHub release page as a repository?
For ex. https://github.com/kiwibrowser/src.next/releases
It's a fast development browser and GitHub's
 version is Foss so that's hard to check every day and download latest version.
Thank you in advance.

**Comment by Iamlooker** [comment]
Thats actually a super great idea, I try to look into it and reply back

**Comment by machiav3lli** [comment]
You can open an issue at IzzyOnDroid, it does exactly that. Detects GH releases and add them to the repo.
