### ISSUE TITLE
Save downloaded apks until they're installed or after a timeout

### ISSUE THREAD

**Issue by jeremiah-miller** [NeoApplications/Neo-Store#189]
It's not a big deal, but I just tried to install an app for the first time with droid-ify and had to go to the settings to allow it to install apps, and when I got back I had to redownload the app. It would be nice if droid-ify held on to the apk till it was installed or at least long enough that I wouldn't have to redownload it after the install process got interrupted. I'm sure this would be useful in other situations too where the install process could get interrupted, like if you get a call right before installing an app

**Comment by Donkey-Doug** [comment]
Or simply save them for 24 hours after install.

**Comment by sudo-nautilus** [comment]
Yeah, it'll be helpful to install an apk file if it's saved to the storage by the app.

**Comment by neekless** [comment]
It used to store downloaded apks in cache but idk why it doesn't anymore.

**Comment by machiav3lli** [comment]
Actually we plan to allow setting a custom download folder (this would cover two issues: retention and only-downloading) , but this won't come with v0.9, it's more a thing for v1.

**Comment by machiav3lli** [comment]
Since couple of releases there's an option to set how long the apks should be cached
