### ISSUE TITLE
Replaced "Update" tab with "Progress" tab

### ISSUE THREAD

**Issue by Pranab009** [NeoApplications/Neo-Store#190]
Please Replaced "Update" tab with "Progress" tab
You can see downloading apps & updateing apps.

![Screenshot_20220303-185404_1_1_1i_1](https://user-images.githubusercontent.com/65340361/156616336-43d0186b-99fc-462f-affd-fb16e8c8ba47.png)

![Screenshot_20220303-185404_1_1_1i](https://user-images.githubusercontent.com/65340361/156616349-e0897bde-dd48-4ded-aa33-0374da482b02.png)

![Screenshot_20220303-185404_1jj](https://user-images.githubusercontent.com/65340361/156616357-522e0db4-3494-4f80-9c6e-da3ef944f406.png)

**Comment by Donkey-Doug** [comment]
Related: https://github.com/Iamlooker/Droid-ify/issues/117
