### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by ciotorcristian** [NeoApplications/Neo-Store#194]
What's up with the rebranding? Were you bought by a company? Can you be more transparent with this? What is the future of the app?

**Comment by NoahAndrews** [comment]
I'm pretty certain nothing was bought, the maintainers just found a much better name (and also teamed up with the maintainers of a couple of other apps to start a unified brand).

**Comment by machiav3lli** [comment]
Here's the link to our announcement: https://t.me/neo_applications/114

Nope the projects weren't bought, rather we (the developers of the three projects) decided to come together and create a collective, as we have similar vision on Android-FOSS development. We surely welcome anyone that would like to join us and make Neo Apps more comprehensive.
