### ISSUE TITLE
App crashes and slows down Android 7 device

### ISSUE THREAD

**Issue by shom13** [NeoApplications/Neo-Store#195]
**Describe the bug**
Crashes from time to time, also freezes

**Expected behavior**
On my android 11 it works fine as expected, but freezes on my older device

**Smartphone

- Device: [e.g. moto]
- OS: [e.g. Android 7]

**Comment by machiav3lli** [comment]
What version are you using? If alpha, then feedback should be given only in the community group.
And a small notice for the (maybe near) future: We're considering dropping A7.
