### ISSUE TITLE
App crashes on Android 12

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [NeoApplications/Neo-Store#197]
### Smartphone

**Device: Samsung S21 5G
OS: Android 12**

**Let me try to explain - So o start the app:**

![neostorev090-alpha2-1](https://user-images.githubusercontent.com/61406324/162267426-9cf931a7-8822-4a47-a306-6329e6c4f47c.jpg)

**And than i think - what is this empty field
ah "All applications" ... is that how it should be ?**

![neostorev090-alpha2-2](https://user-images.githubusercontent.com/61406324/162267776-58606912-0353-4dff-9f77-b9a2456f9c94.jpg)

**and then when I want to click on "Connectivity",
Development", "Food", "Games" and so on,**

**the app crashes.**

**Further feedback comes in extra issues.**

**Comment by machiav3lli** [comment]
Bugs of test builds should be only reported in the group.
