### ISSUE TITLE
Category twice

### ISSUE THREAD

**Issue by Donkey-Doug** [NeoApplications/Neo-Store#199]
Multimedia is shown twice. Once with an additional capital:

![Screenshot_20220410-193839_Droid-ify](https://user-images.githubusercontent.com/50382414/162632161-bddd0f59-ee4c-47e3-a591-23f1775f6463.png)

**Comment by machiav3lli** [comment]
Yeah, it's RFM Radio that's using this very special category "MultiMedia". I don't know if we should override the defined categories!?

**Comment by NoahAndrews** [comment]
Can't we just submit a PR to the repository metadata if it's in the official repo? I'm not sure how that works for Izzy's one.

**Comment by machiav3lli** [comment]
@NoahAndrews done https://gitlab.com/IzzyOnDroid/repo/-/issues/258

**Comment by machiav3lli** [comment]
Fixed
