### ISSUE TITLE
Add a way to update all apps at one

### ISSUE THREAD

**Issue by Rennarde1312** [NeoApplications/Neo-Store#202]
Maybe i missed out on a button but i didn't saw a way to update all my apps at once.

**Comment by NoahAndrews** [comment]
This is already implemented in the alpha version, which you can find in a pinned comment in the Telegram group

**Comment by NoahAndrews** [comment]
This is already implemented in the alpha version, which you can find in a pinned comment in the Telegram group

**Comment by Rennarde1312** [comment]
Thanks a lot, I'm not an huge fan of installing alpha's since I can spend a lot of time fiddling with my phone.
Do you have a way for me to make a small donation ?

**Comment by NoahAndrews** [comment]
It's worth noting that the alpha version installs itself alongside the stable version, not in place of it.
