### ISSUE TITLE
Add an update all button

### ISSUE THREAD

**Issue by CodeCubeNeo** [NeoApplications/Neo-Store#207]
Hello! One improvement I see is to add an update all button in the updates tab, instead of going to every app to click update, since you also cant do paralel downloads.

**Comment by machiav3lli** [comment]
Duplicateof (#3, #202 & 204) and already implemented.
Don't open issues before reading at least the open one and latest closed ones.

**Comment by CodeCubeNeo** [comment]
Yeah sorry, I should have checked more throughly (I only searched for update all). Also when will there be a new release?
