### ISSUE TITLE
Unattended updates not working in Android 12

### ISSUE THREAD

**Issue by Victor239** [NeoApplications/Neo-Store#208]
I was excited to finally upgrade to Android 12 (via LineageOS 19) but now that I have I can't seem to get [unattended app updates](https://github.com/NeoApplications/Neo-Store/pull/159) to work.

I've tried updating several apps via Droid-ify once but they never seem to auto-update after that, and a few apps I reinstalled via Droid-ify don't auto-update either.

**Comment by machiav3lli** [comment]
Cause we haven't done a stable release since then, either join the TG group and test the latest alphas, or just wait for the next stable release (will take time)
