### ISSUE TITLE
Wishlist function

### ISSUE THREAD

**Issue by pusherplayer** [NeoApplications/Neo-Store#21]
I don't know if this posits a problem
But i have always wanted an f droid client to have some sort of wishlist feature 
 
I think it would be great just saving some apps to try out for later when i am on the fence

**Comment by Joeb3** [comment]
I agree, it would be a very useful feature.
Aurora Droid has this feature, but sadly it is much slower than Foxy in syncing repos.

**Comment by Pranab009** [comment]
This is an handy feature.Please add this feature.
See this image.

![Screenshot_20220213-224908_1](https://user-images.githubusercontent.com/65340361/153857752-8a147f37-6d40-4ad2-ae89-25ae22f32ca8.png)

**Comment by XXDRD** [comment]
I agree too, thought the bookmark option should be at top right corner with the share option

**Comment by maverick74** [comment]
I would also like this.

**Comment by Caethelepracaun666** [comment]
K. K. _ .
