### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [NeoApplications/Neo-Store#211]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 20 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on 
Neo-Store (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Neo-Store's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by Iamlooker** [comment]
Hi, Thanks for running your test on our app.
This is really concerning to us and to users of Neo-Store, We would appreciate if you could share the report/gist with us.

**Comment by machiav3lli** [comment]
You may write us both

**Comment by theAkito** [comment]
Please, report this spammer. This is just a bot spamming the very same message to tons of open source repositories. The only things that are changed in the message are the repository's name and the amount of warnings.

**Comment by machiav3lli** [comment]
@theAkito I did, thanks. There's surely other ways to ask for a help in research, instead of writing tens of FOSS projects at once.
