### ISSUE TITLE
Missing Issue

### ISSUE THREAD

**Issue by Balthazar1234** [NeoApplications/Neo-Store#214]
Hello,

sorry if I'm wrong but if i remember right a few days ago a security researcher posted an issue in which he told that he found about 20 security problems in droidify.

If you removed it with reason, i just want to let you know that I'm interested in the outcome and if the app can be used without worries.

Thank you!

**Comment by machiav3lli** [comment]
The account behind the issue have posted in an irregular interval the same message with different numbers (random?) for tens of Android FOSS projects and did reply to non of the developers, so I interpreted it as a spam.

It may be a legitimate scientific work, badly planned & communicated, but it also can be just someone who things hir/her project need some more attention and tried to advertise it.

We already use static analysis tools of code locally and no such warnings has been shown. If not convinced you can always clone the repo and apply your choice of analysis tools or check all dependencies & packages with possible security concerns manually.

**Comment by Balthazar1234** [comment]
Thanks for the detailed answer!
