### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by jbas23** [NeoApplications/Neo-Store#218]
Hi, I am looking forward to Japanese localization.

The Japanese translation seems to be well enough translated, 
but why isn't it added to the language settings? :confused:

<a href="https://hosted.weblate.org/engage/droidify/en/">
<img src="https://hosted.weblate.org/widgets/droidify/ja/localization/svg-badge.svg" alt="翻訳状況" />
</a>

**Comment by Iamlooker** [comment]
I merged Weblate commits.

**Comment by jbas23** [comment]
Thank you :smile:
