### ISSUE TITLE
Adding a Github / Gitlab release page as a Repo

### ISSUE THREAD

**Issue by Jegah** [NeoApplications/Neo-Store#221]
It would be awesome to be able to add open source apps that have a release page directly as repos. 

I know there are repos that sort of do that (e.g. IzzyonDroid) but having to go through a third party for every app we might want do add isn't great and some app aren't being added, for example when the app is already present on fdroid, even when the fdroid version is lagging behind. Other apps like the GrapheneOS Camera need a whole seperate Appstore to be updated without having to go check on Github.

**Comment by machiav3lli** [comment]
Duplicateof #185
