### ISSUE TITLE
Install all works only together with Auto-update

### ISSUE THREAD

**Issue by mahdi1234** [NeoApplications/Neo-Store#235]
v 0.9.0-rc1

_Scenario 1_

Settings:
- Auto-update OFF
- Silent install ON

Tapping "Install all" nothing happens.

_Scenario 2_

Settings:
- Auto-update ON
- Silent install ON

Tapping "Install all" apps are getting downloaded and then installed.

I would say it should work in both modes. My use-case is I don't want app to install directly after refreshing repos. I would like to first review what updates are about and then apply them (likely) all. Have to now toggle the setting all the time.

**Comment by Kreuger** [comment]
How do I get the pre releases? I saw something about telegram but cant find a link.

**Comment by machiav3lli** [comment]
Oh, thanks. That's pretty helpful, it was reported in the group but without such contextual info. I'll get it fixed by next rc.

**Comment by mahdi1234** [comment]
Seems to be fine in rc2, thanks @machiav3lli
