### ISSUE TITLE
Option to bulk-process updates

### ISSUE THREAD

**Issue by madduck** [NeoApplications/Neo-Store#239]
With Droid-ify, for every updated app, I have to click into the app, click update, confirm the update, navigate back, lather-rinse-repeat. F-Droid had a button "download all", which would at least download all apps at once, and then allow me to update them right from the list. It would be great if this could be adopted, and even if a button "update all" could be provided, which downloads them all, and then proceeds to update them all in order, so that all I have to do is confirm each update.

Thanks!

**Comment by machiav3lli** [comment]
It's already implemented and been tested in the community group, so will be in the next stable release (soon).
