### ISSUE TITLE
After Ignoring all the updates of an app the update tab still shows the app update 

### ISSUE THREAD

**Issue by soumyabratabose** [NeoApplications/Neo-Store#242]
![Screenshot_20220707-095346](https://user-images.githubusercontent.com/89439748/177690998-3a64773e-a4b5-4ec8-84f7-00e750a9620c.png)

![Screenshot_20220707-095354](https://user-images.githubusercontent.com/89439748/177691025-fc24ee86-07ad-4d38-8e32-7376db39536b.png)

Expected Behavior : The app should be removed from updates tile.

**Comment by machiav3lli** [comment]
It'll be removed on restarting the app
