### ISSUE TITLE
Screenshots are outdated 

### ISSUE THREAD

**Issue by urmomsangus** [NeoApplications/Neo-Store#245]
Your screenshots still show @Iamlooker Droid-ify on the names.

Example: https://github.com/NeoApplications/Neo-Store/raw/master/metadata/en-US/images/phoneScreenshots/home-light.png

This also affects what screenshots are shown in the store apps (F-Droid, Droid-ify) and not just on the website.

I don't want users to be confused between your app and: 
https://github.com/Iamlooker/Droid-ify

Thanks

**Comment by urmomsangus** [comment]
Looks like you fixed already. Thanks, and best wishes with Neo-Store and the rest of the Neo Applications

**Comment by machiav3lli** [comment]
@urmomsangus thanks!
