### ISSUE TITLE
Trouble to scroll up and update button on app page.

### ISSUE THREAD

**Issue by KorneevVitaly** [NeoApplications/Neo-Store#246]
When trying to scroll app page up, the app always register it as swipe app page away to apps list instead of scrolling it up. Which is annoying.
Also now instead of update button there is always launch button. Which is not convenient.
I think it's a bad design choice.
At least give options for turn this behaviours off.

**Comment by barackenkumpel** [comment]
To scroll up you have to scroll down a little first:

https://user-images.githubusercontent.com/93818968/177928417-71d2543e-0688-4f20-83b5-e3b9c4759123.mp4

Really annoying ...

**Comment by hollisticated-horse** [comment]
I don't think there is need an option to turn if off, but maybe to set it so that you scroll up to the top, and then exit if you scroll higher ?

**Comment by rusty-snake** [comment]
I would say that swiping in the content should move it and swiping down Form the top (APP icon + Name) closes.

**Comment by rusty-snake** [comment]
You can also use the "back" button/gesture.

**Comment by Caethelepracaun666** [comment]
17. 7. . cCc . . O O oO o 0
