### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by fusionneur** [NeoApplications/Neo-Store#252]
After updating an app (even outside neo, eg. Aurora store), a notification is shown that updates are available. Pressing on the notification brings you to installed apps, but no updates are available for any of the neo handled apps

**Comment by EmberHeartshine** [comment]
I have a similar problem: after updating, I keep getting a notification that "0 apps have updates".

Why would I want to be notified of that??

**Comment by machiav3lli** [comment]
Already solved in local branch. Will push when I have time
