### ISSUE TITLE
Option to change the update interval

### ISSUE THREAD

**Issue by rusty-snake** [NeoApplications/Neo-Store#263]
ATM it looks like Neo Store updates the repositories every 20 minutes. To me this looks a bit to frequent and I would like to change it to say 4 hours. This save battery and traffic (both for you and the servers).

**Comment by machiav3lli** [comment]
Yeah, I've done so already in the local codebase, will commit and push when am able to and will be in next release.

On another note, thanks for going through the issues, that helps a lot!
