### ISSUE TITLE
Unable to return install dialog

### ISSUE THREAD

**Issue by Ygarr** [NeoApplications/Neo-Store#264]
If dialog disappears you cannot to return it so you MUST to re-download app and stare at this process
The installation process causes to be controlled by you all the time.
Also what we have: extra app downloads and time waste to control automatic thing

1. We see updatable apps
2. After tap "update" began downloading
3. We see dialog with options "cancel" "install"
4. Some other app or some other short-term reason makes us postpone the installation
5. We lose install dialog
6. After returning to the update process, you must (repeat the entire previous process)again wait for the application to download and catch the installation dialog

**Comment by machiav3lli** [comment]
Should be already fixed in the latest 0.9.3-rc1, will be released in the next days maybe…
