### ISSUE TITLE
[BUG] Neo store redownloads app if app failed to install due to user inactivity in previous attempt

### ISSUE THREAD

**Issue by rsmyst** [NeoApplications/Neo-Store#268]
Basically, if I let an app download but don't click install due to any reason, neo store kinda deletes the donwloaded apk file. 
It doesn't make sense to keep redownloading app everytime you hit install/update. 
Maybe save the apk after download?

**Comment by machiav3lli** [comment]
It should be fixed with latest update, otherwise control over retention time of apks is planned.
