### ISSUE TITLE
[Request] Mastadon comments like G-Droid

### ISSUE THREAD

**Issue by magnus-ISU** [NeoApplications/Neo-Store#276]
I think knowing what users think about an app is essential for an app store, and it is atrocious that the ONLY? Fdroid app which has those is the UI mess that is G-Droid. Having it in Neo Store would be awesome. The date of the comments should also be shown.

**Comment by machiav3lli** [comment]
Nope, there's no plans to do such. There's a lot of arguments against it i.e. maintaining such a parallel structure and managing commentaries are huge projects which noone involved in the project would be ready to take care of.
When F-Droid create such platform I'd be make sure that NL supports it, but I would never open such sub-project, you may take this for granted.
