### ISSUE TITLE
Make it handy

### ISSUE THREAD

**Issue by iBabu007** [NeoApplications/Neo-Store#277]
Make it handy like droidify.
See this images.
You can easily use droidify with one hand.

![Screenshot_20220815-221752ioo_1](https://user-images.githubusercontent.com/65340361/184685416-07faf36b-9d8b-4c83-a6f3-3a7b769234da.png)

![Screenshot_20220815-222936_1](https://user-images.githubusercontent.com/65340361/184685428-a8acd627-d0d7-458c-97ff-1c2abebe0959.png)

**Comment by machiav3lli** [comment]
As soon as the compose library including the scrollable topbar get stable enough, an option will be added for users as this was and is a really controversial topic in the community.

**Comment by machiav3lli** [comment]
Added and then got removed in favor of new design
