### ISSUE TITLE
[Feature Request]Disable Signature & Version Verification

### ISSUE THREAD

**Issue by Muteplayer** [NeoApplications/Neo-Store#287]
I want a option to disable signature verification and version verification when installing a app. 
I update apps from multiple sources, and sometimes I need to do a downgrade, but when I click to install it says incompatible version. So it need to open app link and download apk and Install it.

I already have a patched Package Manager, I don't want to Neo Store patching it, I just want to disable those verification when installing.

**Comment by machiav3lli** [comment]
To be able to see unmatching builds of your apps, enable showing incompatible apps in the install settings.

NS is not meant to be a Patcher replacement or do such!
