### ISSUE TITLE
Cannot install App

### ISSUE THREAD

**Issue by And96** [NeoApplications/Neo-Store#288]
Given all permissions

I got this message everytime I try to install an app on upgrade an app

I am using the latest version

![Screenshot_2022-08-26-15-46-08-687_com.machiav3lli.fdroid.jpg](https://user-images.githubusercontent.com/42185838/186917956-2cc47857-0b56-40d2-8850-be8c8a030764.jpg)

**Comment by machiav3lli** [comment]
You're on MIUI, Xiaomi has bricked Android's API to install apps. Just disable MIUI optimizations to be to install apps.

**Comment by And96** [comment]
Just to share

Official F-Droid works fine.
Download APKs from browser and installing them work fine too
