### ISSUE TITLE
App crashes when checking a newly added repository

### ISSUE THREAD

**Issue by ghost** [NeoApplications/Neo-Store#29]
I'm using it on Android 10 and crashes everytime it checks a newly added repository (already tried multiple repos like Bromite, Kali and MicroG, with and without the fingerprint). Just works fine when you skip check. So this issue don't really make the app unusable.

**Comment by machiav3lli** [comment]
It's already fixed, just wait for the next release.

**Comment by MajinSaaY** [comment]
great c:
