### ISSUE TITLE
Root update is not working

### ISSUE THREAD

**Issue by Amby713** [NeoApplications/Neo-Store#290]
I get notifications that there is an update to an app and doesn't install by itself. I have to click on update and then it does silent install. How do I just let it update without any input from me?

**Comment by machiav3lli** [comment]
What's your android version? What version are you using? Do you have root?

It's always good to give some contextual information when opening an issue.

**Comment by Amby713** [comment]
Android 11

version 0.9.4

Rooted and approved neo tp use root

**Comment by mase76** [comment]
Same here. Crdroid 8.8 (Android 12) with root (Magisk). Latest version of Neostore from Fdroid Repo.

**Comment by yeswap** [comment]
No auto-updates for me either rooted Pixel 3XL, LOS 12.1.

**Comment by gbakeman** [comment]
I thought this was a recent issue; root install stopped working for me after the latest update (0.9.13?), on a OnePlus 6T with Android 9.

**Comment by machiav3lli** [comment]
Update to 0.9.14, it should be fixed

**Comment by soredake** [comment]
@machiav3lli root update is still not working for me.

**Comment by gbakeman** [comment]
@soredake they've been working for me, could you verify a few things?

- On version 0.9.14
- Installer type is root installer
- your root management app has Neo Store set to allowed
- Other root apps still function

**Comment by gbakeman** [comment]
> @gbakeman yes to all, i found out that if set repository sync to something like 1440 minutes silent update is not working, setting it to 60 minutes makes it work after some time.

Perhaps there's some battery/power management function killing Neo Store?

**Comment by soredake** [comment]
It's aosp based rom and battery saving for neo store is set to "unrestricted".
