### ISSUE TITLE
[Feature Request] Hide Apps (blacklist) from Explore/Latest

### ISSUE THREAD

**Issue by hahalolha** [NeoApplications/Neo-Store#291]
Feature request for the ability to choose apps to be hidden from the Explore/Latest tab. Some Repos' have apps which are constantly updated and are hence, placed on the top of the Explore/Latest queue making it somewhat cluttered and difficult to discover new apps. Feature would be useful when, for example, an application from the Calyx repo is desired without the specific Calyx OS components. 

See screenshot below for example:
![Screenshot_20220903-151537_Neo Store.jpg](https://user-images.githubusercontent.com/93250867/188256984-8a5e6e61-519b-4088-9236-338a0d451317.jpg)
_Image Description: 'Explore' page of Neo Store with cross-hatching indicating 'unwanted' applications which should be hidden with use of a blacklist/denylist._ 

This is my First Issue/FR ever so please be nice 😁

**Comment by machiav3lli** [comment]
Duplicate #121
