### ISSUE TITLE
[Request] handle f-droid.org links

### ISSUE THREAD

**Issue by tennox** [NeoApplications/Neo-Store#296]
I'd love to be able to open f-droid.org links directly in this app :)

`https://www.f-droid.org/en/packages/com.machiav3lli.fdroid/`

Not sure if this is feasible for other repos as well...?

**Comment by NoahAndrews** [comment]
It already can, but on modern versions of Android you have to enable it manually from Neo Store's App Info page. Select Open by default, then Add Link, then select f-droid.org.

**Comment by tennox** [comment]
Oh, that's a great tip - thanks :+1:
