### ISSUE TITLE
Download progress bar not completed for root-enabled installs (old device)

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#299]
For regular non-root installs, the APK download bar goes to 100% before showing the install prompt (or installing directly if possible on A12).

But for root installs, the bar only goes to (what looks like) 50% before vanishing while the app is installed. It should go to 100% in this case as well.

Edit: This turns out to be a problem only for an older device that has a presumably slowed down CPU. A modern device goes to 100% correctly. So maybe the solution this is looking for is to update the progress bar at fewer, more spaced-out intervals, so that older devices can keep up.

**Comment by opusforlife2** [comment]
Thanks!

**Comment by opusforlife2** [comment]
Surprisingly, this didn't seem to work. There is no discernible improvement in how far the download bar gets before being replaced. It's still between 1/4th and 1/2.

**Comment by opusforlife2** [comment]
Never mind. The bar is filling fully. It didn't work immediately after the update, but the device has been restarted a couple of times since then. So it might have been just that.

**Comment by opusforlife2** [comment]
@machiav3lli Sorry about the flip-flopping. The problem remains. Whenever the CPU is slowed down due to carrying out some other task in the background, or being hot from charging, the download progress bar stutters here and there and fails to reach the end before installation starts. So the UI updates are still being sent too fast for the CPU to show in real-time.

**Comment by OkyDooky** [comment]
It is still a problem for me, as well. The progress bar hits an incosistent point befire the end and the install begins. It isn't exactly at 59% marker, either. Sometimes it's higher and sometimes it's lower.
