### ISSUE TITLE
Cancelling a download slightly broken

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#301]
This only happened once. Mid-way while downloading an app, I tried to cancel it. The download bar got stuck at that point. The download notification's cancel button didn't do anything either, nor could it be swiped away.

It was solved by closing and reopening the app sheet. The Install button showed up (despite the paused download notification) and it could then be used to resume and cancel the download freely.

**Comment by machiav3lli** [comment]
This should be fixed on 1.0.0
