### ISSUE TITLE
Show individual app changelog

### ISSUE THREAD

**Issue by Victor239** [NeoApplications/Neo-Store#306]
F-Droid official app shows the changelog for apps which provide them (e.g. Element) so users can easily see what new features or changes can be expected when updating the app.

**Comment by machiav3lli** [comment]
Changelog of the latest release if available is seeable under permissions' block

**Comment by Victor239** [comment]
Oh right, I didn't expect it at the bottom of the page. Maybe move it to the top if you already have the app installed and are just updating?
