### ISSUE TITLE
Dark theme improvement

### ISSUE THREAD

**Issue by Donkey-Doug** [NeoApplications/Neo-Store#31]
I suggest an implementation in which the user can choose for:

- Light theme
- Dark theme
- Follow system settings

And finally, dark theme should have an option for dark grey and pure black. I like pure black, but I also want to be able to switch to light theme when I turn off dark mode from my notification toggles. Currently follow system and pure black are 2 seperate options.

Like this:
![Screenshot_20211016-001629_Redditoria_1](https://user-images.githubusercontent.com/50382414/137562645-55a51271-5058-4a81-90f5-ac9fc8741c8d.png)

**Comment by Iamlooker** [comment]
![Screenshot_20211016-113340_Droid-ify](https://user-images.githubusercontent.com/60404093/137575856-5456d220-9a4c-438c-b4ab-9dc10e9c0a59.png)
