### ISSUE TITLE
Clarification on updates of an app

### ISSUE THREAD

**Issue by c-key** [NeoApplications/Neo-Store#313]
Is it right that an automatic update of an applications will be downloaded from the installed repository? Like the code from here https://github.com/NeoApplications/Neo-Store/blob/master/src/main/kotlin/com/machiav3lli/fdroid/service/SyncService.kt#L452
Or is it possible that an application can be updated from another repository?
In the detail information of an app, I see on which repositories the app will be available and it could be more than one.
So it can not be possible on automatic update that an app can be updated from another repository, right?

**Comment by machiav3lli** [comment]
The signature of a package is the main factor to decide if a package is "compatible" or not. So if two repos use the package with the same signature (functionally same distributor), then the package can be cross-updated.
