### ISSUE TITLE
Follow google design guidelines

### ISSUE THREAD

**Issue by Donkey-Doug** [NeoApplications/Neo-Store#323]
The app has a little bit of a makeover in version 0.9.6, but it looks out of place on android.

For an example of an app with similar design but more in line with google's guidelines, take a look at libretube:

![Screenshot_20221006-115733_LibreTube](https://user-images.githubusercontent.com/50382414/194284440-12dab900-64d1-45a5-8a33-0bd17ca5a204.png)
![Screenshot_20221006-115747_Neo Store](https://user-images.githubusercontent.com/50382414/194284459-79ee2312-4169-49e5-a94f-c46709627abf.png)

**Comment by machiav3lli** [comment]
1. I'm still not settled if it should go or not. I'll try it in next iteration
2. Filled nope, smaller maybe for the TopBar
3. Will stay like this for now, Material standard BottomBar doesn't provide enough contrast of selected item for people with some sorts of color-blindness
4. Chips design is still a thing to revamped, so yeah…
5. a big NO for 3 dots

I understand your approach to this, but I don't feel bound to respect the guidebook.

**Comment by Donkey-Doug** [comment]
Version 0.9.7 already looks a lot better
