### ISSUE TITLE
"Latest" tab is kinda redundant now

### ISSUE THREAD

**Issue by oliverlew** [NeoApplications/Neo-Store#325]
Current (v0.9.6) Latest tab consists of two sections: New apps and Recently updated.

But with the new sort and filter options in each tab, those can be achieved with sorting by "date updated" and by "date added".

I would prefer to merge those two tabs like this:
- Remove "latest" tab
- Move the original "New apps" section to the top of "Explore" tab. This is because I think it's important to support new apps, so users can see them under any sort and filter. Also, the code wouldn't be wasted.
- Show sort order in currently "Sort and filter" button. Use the sort icon to inform the user that it's a button with more options. I.e., `<ascending_sort_icon> Name`, `<descending_sort_icon> Updated`.

**Comment by machiav3lli** [comment]
Explore still didn't take its final form, which wouldn't avoid having this redundancy, so this is invalid for now. But thanks for the engagement
