### ISSUE TITLE
Remove background color

### ISSUE THREAD

**Issue by Donkey-Doug** [NeoApplications/Neo-Store#329]
So many things in this app have a background, making it difficult to read the text in front. The background around "show more", the current installed version and the information chips make sense, but all the others should just be normal.

![Screenshot_20221011-202423_Trebuchet](https://user-images.githubusercontent.com/50382414/195170863-a365475c-cbf2-4cf5-9e67-575117a664f9.png)

**Comment by machiav3lli** [comment]
I understand your argument, but, using the different backgrounds has the function of allowing users to identify touch-targets better  and separating the different instances of e.g. releases
