### ISSUE TITLE
[FEATURE REQUEST] Allow users to use the previous material design iconography

### ISSUE THREAD

**Issue by ChristenEdmundson** [NeoApplications/Neo-Store#331]
Neo store got an update recently that changed the icons. It'd be nice if users could choose to use the previous material design icons that match android, and other material design apps. Especially since part of the stated description of the app is that it's an f-droid client that uses material design 3.

**Comment by Pranab009** [comment]
Yup, I don't like it's recent icon design.
If possible then add an option to change/select icon.

**Comment by ThatOneCalculator** [comment]
Agreed.

**Comment by machiav3lli** [comment]
Sorry but am no planning to maintain two designs. I'll fix the app description then to fit the app's state
