### ISSUE TITLE
Search results replaced by explore toplist results (race condition) 

### ISSUE THREAD

**Issue by tennox** [NeoApplications/Neo-Store#335]
https://user-images.githubusercontent.com/2084639/196029941-f6404c1d-9dfe-4b92-a59f-82b620fab8aa.mp4

When i open the app and quickly search something, the results are after a moment replaced with the store's "explore" list. Changing the search time will revert the results back to the search results and it then stays that way.

Feels like a race condition where the toplist is still loading (I have slow network) in the background and replaces the search results once loaded.

**Comment by machiav3lli** [comment]
#337 is more comprehensive so I'll close this.
