### ISSUE TITLE
search bar has bad ux

### ISSUE THREAD

**Issue by alexmo1997** [NeoApplications/Neo-Store#337]
there are some things about the search bar which are really annoying when using it (in my opinion)
Edit: Sorry if this sounds a bit harsh, but I just set up a new phone and installing multiple apps was really frustrating like this.

- searching takes ages (if the repo is synced locally, shouldn't it find the apps in an instant?)
- if you press the X, the search bar is closed but the search query is remembered
This is contrary to all other examples where there is such an X in a search bar, where the search query field is cleared but the search bar is kept open. This is really confusing to use. Instead, X should clear the search query and there should be a "←" arrow to the left of the search bar that closes it (and it should probably also clear the search bar)
I just looked at two apps at random (NewPipe and Instagram) and both do it exactly like I just described
- also #335, but I guess that is a already a separate issue

**Comment by machiav3lli** [comment]
The mentioned issues have resulted of the still-not-ended migration to compose, so, they'll be fixed soon enough.

**Comment by machiav3lli** [comment]
These are already sorted out in 0.9.8 (search still takes some time relatively to number of apps to be filtered - the longer the word the faster)
