### ISSUE TITLE
Add TwinHelix Signal-FOSS repo to the list

### ISSUE THREAD

**Issue by m3thm4th** [NeoApplications/Neo-Store#346]
https://fdroid.twinhelix.com/fdroid/repo?fingerprint=7B03B0232209B21B10A30A63897D3C6BCA4F58FE29BC3477E8E3D8CF8E304028

https://www.twinhelix.com/apps/signal-foss/

**Comment by m3thm4th** [comment]
Thank you and thank TwinHelix for providing the repo

@tw-hx there are other third-party clients for F-Droid like
[Droid-ify](https://github.com/Iamlooker/Droid-ify)
[Aurora Droid](https://gitlab.com/AuroraOSS/auroradroid)
[G-Droid](https://gitlab.com/gdroid/gdroidclient/)
[F-Droid Classic](https://git.bubu1.eu/Bubu/fdroidclassic)
[Foxy Droid](https://github.com/kitsunyan/foxy-droid)
[M-Droid](https://github.com/SkyzohKey/M-Droid)
you should get your repository listed in those clients as well

**Comment by machiav3lli** [comment]
@m3thm4th a small side note: majority of the mentioned projects is abandoned
