### ISSUE TITLE
Allow clear text traffic for non https repos

### ISSUE THREAD

**Issue by LironMat** [NeoApplications/Neo-Store#348]
After serving a private local repo on a non secure url (http://) for testing purposes, trying to add the repo to the repos list results in a message: "could not sync ... Network Error".

Modifying the manifest by adding networkSecurityConfig with cleartextTrafficPermitted="true" appears to solve the problem.

**Comment by alanorth** [comment]
I need this too. My repository is only accessible via my own private Tailscale network and is served on plaintext HTTP.

**Comment by machiav3lli** [comment]
Should be fixed with latest alpha (available through the community groups and TG channel for test), please test and report back

**Comment by machiav3lli** [comment]
Fixed on 1.0.0
