### ISSUE TITLE
Screenshot appearance (sliding in from the side) has stuttering

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#352]
When an app sheet is opened, screenshots don't appear smoothly. The leftmost image 'boxes' that load first usually have to slide to the right to make room for more boxes. This animation has a lot of stutter in it.

Maybe the loading order could be changed so that the first image loaded is always the one intended to be the left-most, etc.

**Comment by machiav3lli** [comment]
Should be fixed on 1.0.0
