### ISSUE TITLE
Battery Optimization not turned off

### ISSUE THREAD

**Issue by paulverbeke** [NeoApplications/Neo-Store#360]
When I first start the app I receive the 2 popups asking to turn off Battery Optimization and allow app to always run in background but after this I checked and "Battery Optimization" was still on "Auto Optimize" and "Allow background activity" was off.
OnePlus 8T Stock OS (OxygenOS 12.1) Android 12
no root or anything special...pure stock
Neo Store 0.9.9

**Comment by machiav3lli** [comment]
Can you please test this on 1.0.0. Thanks

**Comment by paulverbeke** [comment]
Still on OnePlus 8T but not on stock OS anymore. Now I'm on PixelExperience 13 (Android 13), and problem is no longer here !
