### ISSUE TITLE
Missing results in the search vs F-Droid app

### ISSUE THREAD

**Issue by Primokorn** [NeoApplications/Neo-Store#372]
Hello,
Many results are missing when I search using Neo Store. I use the following repositories: F-Droid + Izzy + Calyx
F-Droid repo is the only used in the F-Droid app.

Here is a comparison:

![Screenshot_20221205-101313207](https://user-images.githubusercontent.com/5938828/205599766-1d3d2eff-1867-4357-9cea-3a1e3fb4b835.jpg)
![Screenshot_20221205-101222082](https://user-images.githubusercontent.com/5938828/205599774-4d6e7c71-b862-497f-b43e-fd7e2e14c47a.jpg)

Neo Store v0.9.10

**Comment by machiav3lli** [comment]
Not really missing, it's just that you're searching in the latest bar which only shows only a certain number of the latest apps (100 by default), while explore is the tab you should be searching in.

**Comment by Primokorn** [comment]
That's right, I'm sorry... Thank you for the help.

**Comment by GeorgGa** [comment]
I don't know if I am doing something (could I have possibly changed something in settings?) wrong or if I should open a new issue for that: 
I am using NeoStore version 1.0.9 and face the issue that results from the F:Droid repo are suppressed when using it together with the IzzyOnDroid repo.
E.g. searching for "Etar" delivers no results when F-Droid + IzzyOnDroid repo are enabled, but brings up one item when only the F-Droid repo is enabled.


Edit: Nevermind. Version 1.1.0 seems to have fixed the issue I had.
