### ISSUE TITLE
Crash when selecting update notification the first time

### ISSUE THREAD

**Issue by adiOdi** [NeoApplications/Neo-Store#374]
Android 13, OneUi 5
Hi! The app crashes every time I select the notification where it says "updates available", but the notification still stays up. When I click it again, it just works and brings me to my "installed apps" screen.

Is there a possibility to create a log to share?

**Comment by machiav3lli** [comment]
Can you please test if this happens in the latest release 0.9.12 and report back. Thanks!

**Comment by n2burns** [comment]
I also experience this issue. I am on 0.9.12.

**Comment by machiav3lli** [comment]
Should be fixed on 1.0.0
