### ISSUE TITLE
UI/UX gets very confusing when multiple apps are being auto-updated

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#375]
If the app is set to auto-update, and there are updates available for multiple apps:

- The notification goes crazy, switching between showing all the parallel downloads one by one. This should be replaced by either one notification per download, or a UI solution that shows the download states of each app, while the notification only shows the combined state, or just text saying downloads are ongoing.
- The Install screen/dialogue shows randomly for each app that has finished downloading. Since there is no installation UI yet (see #297), this can get very confusing, very fast. Has one app finished installing by the time the other one's Install prompt shows up? No idea. No idea how long one should wait, either, since another app might finish downloading and show an Install prompt meanwhile. Can multiple Install prompts start piling up, and does that create any issues?
- Moreover, once one app has finished installing, the other apps' download status vanishes. A user could easily end up downloading them again if they don't know what's going on.

The simplest stopgap solution that occurs to me is to download and install serially instead of in parallel. Isn't that how Play Store also does it?

**Comment by machiav3lli** [comment]
There'll be a download UI soon enough + reformatting the notification channel to be more multi-downloads friendly (the second possibly before the first). It will take sometime, as am now pretty busy with private life, I think you may survive couple of weeks/months without a fix.
