### ISSUE TITLE
auto sync starting even if not plugged in

### ISSUE THREAD

**Issue by fusionneur** [NeoApplications/Neo-Store#378]
i have the option to auto sync only when on wifi and plugged in. however looking in network connection log (netguard app), i can see the requests towards repos every 2 hours (i set auto sync to 120 m), even when phone is not plugged

**Comment by machiav3lli** [comment]
There's already an alpha release in the comunity groups (Telegram or Matrix), you may test it and report back. There's no ETA for a stable release.
