### ISSUE TITLE
An error occurred while installing the app

### ISSUE THREAD

**Issue by Noah-will** [NeoApplications/Neo-Store#380]
I choose the legacy installer(compatible with MIUI) in the Installer type, and then I download a program and click Install, the  neo-store program exits directly, but when I  choose the other two installers, there are no problem.

Mobile operating system is PixelExperience.

**Comment by machiav3lli** [comment]
Please check the latest release 0.9.12 and report back if fixed

**Comment by machiav3lli** [comment]
Fixed on 1.0.0
