### ISSUE TITLE
Show warning about security vulnerability

### ISSUE THREAD

**Issue by tennox** [NeoApplications/Neo-Store#382]
I noticed this while trying the F-Droid app, and upon comparison with the beloved NeoStore realized this is missing:
A visible warning about security vulnerabilities.

Known vulnerable apps are flagged with an Anti-Feature in F-Droid:
https://monitor.f-droid.org/anti-feature/KnownVuln

And here's one current example:
https://www.f-droid.org/en/packages/com.saverio.pdfviewer/

NeoStore is showing it in anti feautes list, but one needs to check manually in order to see it.

Best would be:
1. A visible indicator warning on the app detail page (when considering to install)
2. Some warning when an app is already installed, like f-droid does it (except maybe less ugly 😅)
![Screenshot_20221218-161617_F-Droid.png](https://user-images.githubusercontent.com/2084639/208306155-135cd257-377a-4ce4-a02a-356f485e4b38.png)
![Screenshot_20221218-161624_F-Droid.png](https://user-images.githubusercontent.com/2084639/208306157-1bca983f-7bcf-49e1-86d7-49d2971e8599.png)

**Comment by machiav3lli** [comment]
Here's a look on the implementation

![Screenshot_20230105-155206_Neo Store-Debug](https://user-images.githubusercontent.com/40302595/210809354-7951af99-f165-454b-8d2b-a406f29a319a.png)

![Screenshot_20230105-155243_Neo Store-Debug](https://user-images.githubusercontent.com/40302595/210809365-4cb35fdc-159d-4932-9878-dfea600824ff.png)
