### ISSUE TITLE
Unable to install updates gives invalid apk error

### ISSUE THREAD

**Issue by kaosine** [NeoApplications/Neo-Store#388]
Trying to install updates to my apps and it keeps giving me invalid apk errors in my notification shade(which is the only place I see it). Even hitting the update button in any of the apps I have updates for does nothing to actually update it. I'm able to install new apps just not update.

I'm on oneui 5.0 and android 13 on base model s22. I even updated using the latest release from yesterday and nothing. Updates remain stuck still.

**Comment by kaosine** [comment]
Changes to the miui compatibile installer session and it works. Seems it's a issue with the default installer.

**Comment by D4rklord07** [comment]
Same issue here but in my case the app closes immediately and crashes. And also can't even install apps, it just crashes. Using miui compatible installer did nothing.

I'm on miui 11 Android 9.

**Comment by kaosine** [comment]
> Same issue here but in my case the app closes immediately and crashes. And also can't even install apps, it just crashes. Using miui compatible installer did nothing.
> 
> I'm on miui 11 Android 9.

Which is odd bc mine is now doing the same thing.... But I'm on a s22 so idk what's going on here. I may try switching the installer session back but I was keeping a eye out for a updated binary to install on my phone. Makes the app a digital paperweight so to speak if you can't update or install stuff....

**Comment by machiav3lli** [comment]
Any crash logs?

And some useful information:
- In what version are you facing this?
- Do you have root?
- Which installers did you test?
