### ISSUE TITLE
Add option to hide category sidenavbar

### ISSUE THREAD

**Issue by Elbullazul** [NeoApplications/Neo-Store#390]
**Is your feature request related to a problem? Please describe.**
Navigation by category is great, but not used very often. Having it on-screen all the time doesn't look quite right, specially with the more squeezed out app list.

**Describe the solution you'd like**
Having an option to toggle it on or off in the settings, or better yet, have it slide out like a sidebar in some other apps.

**Comment by ThatOneCalculator** [comment]
Or just don't make it vertical. Worst neo store decision yet.
