### ISSUE TITLE
Long-press on source link button will leave a lingering toast open

### ISSUE THREAD

**Issue by EtiamNullam** [NeoApplications/Neo-Store#391]
Long-press (hold) on source link button will open toast, saying it was copied to clipboard, which won't close on its own until exit from app details. There is no way to dismiss it unless "Open" is pressed.

I think it should be dismissed automatically rather quickly, otherwise we can just press it to open in browser directly.

Neo Store version: 0.9.12

**Comment by machiav3lli** [comment]
Yup, am aware of it and will be fixed in the next release

**Comment by machiav3lli** [comment]
This should be already fixed now
