### ISSUE TITLE
Auto-sync interval input field completely broken

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#407]
On 0.9.13, trying to modify the field exhibits very odd behaviour. Removing digits eventually causes the number 15 to show up. And adding digits eventually causes 43200 to show up. These seem to indicate the min-max values of the setting, which is fine.

The problem is that this _actively_ interferes with user input. Trying to erase the entire thing and entering your own value doesn't work. That 15 stubbornly stays there. You have to manually shift the cursor forwards and backwards while entering and deleting singular digits to be able to prevent that default snap back to 15. Same with 43200.

The most straightforward solution seems to be to have something like `15 - 43200` shown as grey background text if the field is empty, and let the user type whatever they want. If the value is out of bounds, then the field can simply reset to the default value of 60.

**Comment by machiav3lli** [comment]
Yeah am aware of this UX issue, but I still have to settle for solution. 0.9.13 respects the system's minimum interval for planned service jobs (it is usually 15 minutes. It's changed to not allow users to misunderstand it as a bug, when they select 10/5 minutes), while the max is 30 days for now.

**Comment by machiav3lli** [comment]
I'd prefer to make the limits more explicit than a hint on the empty field. Possibly an always visible note.
