### ISSUE TITLE
Root installation with version 0.9.13 

### ISSUE THREAD

**Issue by Primokorn** [NeoApplications/Neo-Store#408]
Hello,
I now have the pop-up to install apps manually. It's no longer done in the background.
Android 11 with Magisk 23.0
Thank you.

**Comment by citizenserious** [comment]
Same on 
Android 10 (LOS 17.1) with Magisk 25.2 
and on 
Android 11 (LOS 18.1) with Magisk 25.2

**Comment by lefterisgar** [comment]
Can confirm on LineageOS 20 (Android 13).

**Comment by Flouzr** [comment]
Same issue here.
Android 11 (DotOS) Magisk 25.2

**Comment by machiav3lli** [comment]
Please test 0.9.14-alpha01 and report back. Should be already fixed

**Comment by IngwiePhoenix** [comment]
Same on 0.9.13, LOS 20.0, Magisk 25.2

![Screenshot_20230130-223154_Magisk.png](https://user-images.githubusercontent.com/2893716/215599750-c57c4b85-57fd-4782-9b53-debdf1af7436.png)

![Screenshot_20230130-223232_Magisk.png](https://user-images.githubusercontent.com/2893716/215599810-01b4bf54-0f37-4b02-bed3-8e80ec6ef895.png)

![Screenshot_20230130-223251_Neo Store.png](https://user-images.githubusercontent.com/2893716/215599882-3432e7c7-f138-48e0-9bce-74a5b7d8f843.png)

![Screenshot_20230130-223337_Einstellungen.png](https://user-images.githubusercontent.com/2893716/215600017-12075c22-f39d-4f6c-9d29-249a13b55441.png)

**Comment by Primokorn** [comment]
Fixed with the alpha release 👍
