### ISSUE TITLE
Repo is sometimes not deletable or info is cut off

### ISSUE THREAD

**Issue by meenbeese** [NeoApplications/Neo-Store#412]
This is actually two separate issues that are closely tied together. 

1. Sometimes you cannot scroll up on a repository info when you long press it, and the card glitches. Some of the info is cut off.
2. Sometimes there is no option to delete or modify a repository when you long press it.

These issues happen is about all of the repos that I tested. It doesn't seem to be tied to a specific one.

In the previous versions, you do these easily, but in the current version (0.9.13), it only seems to work sometimes. Maybe 1 out of 20 times. 

My device is Redmi Note 10 Pro.
It is currently running Android 12.

This is hard to describe by text, so I added a few screenshots below.

First issue (actual result):
![image](https://user-images.githubusercontent.com/114044633/215608144-58b178df-03de-43f5-a3f9-caba62f8938d.jpeg)

Second issue (actual result):
![image](https://user-images.githubusercontent.com/114044633/215608474-b9928bdb-2da6-4084-a1e6-b77e5d93e492.jpeg)

Expected results (for both):
![image](https://user-images.githubusercontent.com/114044633/215608294-30456f33-c30e-427f-aeeb-42e9ae1683eb.jpeg)

**Comment by machiav3lli** [comment]
The combination of traditional BottomSheet and Compose in it is still buggy, but fortunately BottomSheet was added to Compose Material3 finally and the hack will be replaced in the next release (which should fix the issue)

**Comment by machiav3lli** [comment]
Should be now fixed in the just-released 1.0.0-alpha01 (downloadable from the community groups or channel)
