### ISSUE TITLE
Filipino `fil` and Tagalog `tl` translations might contradict with each other

### ISSUE THREAD

**Issue by IverCoder** [NeoApplications/Neo-Store#416]
![Screenshot_20230204_052310](https://user-images.githubusercontent.com/92661164/216760970-fbcacd16-f566-4589-ac17-a9182fe9824c.png)
For context, Filipino `fil` and Tagalog `tl` are practically the same language, which had to be technically separate languages due to legal reasons (read: Filipino is a carbon copy of Tagalog). Anyway, we have stopped calling it "Tagalog" and have largely moved on to "Filipino".

Android recognizes both `fil` and `tl` for app localizations when the system language is set to "Filipino (Philippines)". And that's where I'm worried, as Weblate has both these languages and they might end up conflicting with each other upon installation.

Since the Tagalog `tl` translation has been inactive (and inaccurate from my perspective), can we remove it to avoid conflicts?

**Comment by machiav3lli** [comment]
Done

**Comment by IverCoder** [comment]
Thank you!
