### ISSUE TITLE
installed apps are only partially displayed

### ISSUE THREAD

**Issue by olsching** [NeoApplications/Neo-Store#422]
Hello,
installed apps are only partially displayed.

Version 0.9.13 german

**Comment by machiav3lli** [comment]
Fixed in 0.9.14-alpha01 (available in the community groups).

**Comment by olsching** [comment]
Hello, thank you for the answer!
Where i can find this community groups ? ☺️

**Comment by machiav3lli** [comment]
All are linked in the project's readme: https://github.com/NeoApplications/Neo-Store
