### ISSUE TITLE
Aktivität a Repo

### ISSUE THREAD

**Issue by Hibernd** [NeoApplications/Neo-Store#428]
It's not possible to aktivate a ne repo.

fdroidrepos://raw.githubusercontent.com/chrisgch/tca/master/fdroid/repo?fingerprint=3576596CECDD70488D61CFD90799A49B7FFD26A81A8FEF1BADEC88D069FA72C1
Is this a Bug?

**Comment by machiav3lli** [comment]
Do you mean activating Total Commander Android's repo or being unable to see the apps included (duplicate of #385)?

**Comment by Hibernd** [comment]
I can activate this Repo
fdroidrepos://raw.githubusercontent.com/chrisgch/tca/master/fdroid/repo?fingerprint=3576596CECDD70488D61CFD90799A49B7FFD26A81A8FEF1BADEC88D069FA72C1

But i can't see any Apps. With the F-Droid App it works!

Thank you for your support!
Bernd

*Von: *machiav3lli ***@***.***>
*An: *NeoApplications/Neo-Store ***@***.***>
*Kopie: *Hibernd ***@***.***>; Author ***@***.***>
*Datum: *21.03.2023 09:36:09
*Betreff: *Re: [NeoApplications/Neo-Store] Aktivität a Repo (Issue #428)

**Comment by machiav3lli** [comment]
Then it's a duplicate of #385
