### ISSUE TITLE
Repos not syncing with wifi restrictions and long intervals

### ISSUE THREAD

**Issue by vertigo220** [NeoApplications/Neo-Store#432]
As mentioned in issue #431, I had to manually sync my repos as they had not done so on their own for weeks. I have it set to sync every 1440 minutes (24 hours) only on Wi-Fi, and I'm rarely on Wi-Fi, the last time being a couple weeks ago, actually twice in one day, yet neither of those times were taken advantage of by the app to sync, evidenced by the fact it didn't show the newest version of an app that had been updated almost a month ago.

**Comment by socynx** [comment]
Same problem happens to me. However, I'm always connected to WiFi practically all day and night and the update notification no longer appears. I have to be doing it manually.

Device: Redmi 9
Android: 13
Store version: 0.9.15
Rom: LineageOS 20.0

**Comment by machiav3lli** [comment]
Should be fixed with latest alpha (available through the community groups and TG channel for test)
