### ISSUE TITLE
Allow to install older app versions

### ISSUE THREAD

**Issue by FadeDave77** [NeoApplications/Neo-Store#433]
It would be great if the app would attempt to install the old version over the new one, and then throw an error only if the install was unsuccesful. (see: letmedowngrade;corepatch magisk modules)
Thank you.

**Comment by ascendbeing** [comment]
I like this. the newest version doesn't report which repo failed to sync. fkr example for me it says stacks wallet failed to sync, but I do not have that one enabled. so I'd like to downgrade

**Comment by FadeDave77** [comment]
Oh, I may not have worded my query correctly. I would like the NeoStore app, to allow us to install older versions off applications in the fdroid repo, not the app itself. Although that would also be great, but i think it is limiting that you can't downgrade apps directly in the store, and you have to download the apk to manually downgrade. (For example "Frost for facebook" has a bug in their latest release, and i couldnt downgrade, because neostore told me that I can't, even though I can, because I have the corepatch magisk module installed)
