### ISSUE TITLE
Store is empty

### ISSUE THREAD

**Issue by dylanh724** [NeoApplications/Neo-Store#435]
Android 13. Samsung Galaxy S20+ stock.
F Droid store works fine; just this one is empty.

![Screenshot_20230224_172117_Neo Store](https://user-images.githubusercontent.com/8840024/221140900-5cc65b65-5977-40af-9137-475da19e6a28.jpg)

**Comment by machiav3lli** [comment]
Tap the refresh button on top-right to sync repositories!

**Comment by dylanh724** [comment]
> Tap the refresh button on top-right to sync repositories!

Whew, that's really not intuitive for first-run: Why this unexpected flow? If empty and there are default repos, it'd make sense to load them on first load. This turned out to be a UX issue.

**Comment by machiav3lli** [comment]
I wouldn't see it like that, some users may prefer to use specific repos and not the ones pre-active (based on some privacy/security concerns), this is why I chose not to auto-sync on first launch.
