### ISSUE TITLE
Wrong Version detection in Firefox Clear (so far)

### ISSUE THREAD

**Issue by RazielKanos** [NeoApplications/Neo-Store#437]
I am running Firefox clear currently on version 110, but Neo-Store permanently shows me a warning that Firefox Clear 8.4 has a security issue and I should update. It also doesn't show any newer versions that 8.4

It would be wonderful if I can turn this notification off or remove the wrong identified app from its checklist

**Comment by machiav3lli** [comment]
Will come in the next release
