### ISSUE TITLE
"Could not sync[...]" lies in .15 latest version 

### ISSUE THREAD

**Issue by ascendbeing** [NeoApplications/Neo-Store#443]
Before this version it was fine. now in one sync run it sends two notifications that stack wallet couldn't sync, despite the fact that that repo is disabled. I tried stopping, clearing app data, and restarting from scratch, and it still does this. before I did that, I had enabled and disabled stack wallet repo. after doing stop and clear data and never enabling stack wallet repo, problem persists.

EDIT: To clarify what I am getting at is instead of telling me which repo won't sync, all notifications point me to stack wallet repo, which isn't enabled, instead of which repo is actually failing to sync 

In version .14 this works fine. doesn't in .15 specifically

**Comment by machiav3lli** [comment]
Fixed with #448
