### ISSUE TITLE
Bug. Why are there so few pictures?

### ISSUE THREAD

**Issue by Wjxfi** [NeoApplications/Neo-Store#446]
not usable

![321286.jpg](https://user-images.githubusercontent.com/113500363/222807487-fec23d9a-7b6f-4fd1-9f43-e801a3f53c70.jpg)

**Comment by machiav3lli** [comment]
Many apps still use legacy formats and doesn't provide current icons. Some apps have fixed theirs since reported by the users on the respective projects (check #273, #95).
