### ISSUE TITLE
Silent (root) install freezes app

### ISSUE THREAD

**Issue by another-sapiens** [NeoApplications/Neo-Store#45]
**Describe the bug**
Droid-ify freezes while installing any app after activating Silent Install. 
The installation is still successful.

**To Reproduce**

1. Go to Settings
2. Activate Root/Silent Install 
3. Install any app
4. Droid-ify will freeze for a few seconds.

**Expected behavior**
The installation does not freeze the app.

**Smartphone (please complete the following information):**

- Device: Samsung A10s
- OS: Android 10
- Version: Latest

**Additional context**
It does not pose a problem at the moment; but might become a bit inconvenient if batch updates are implemented down the line, as each installation could trigger the freeze.

I might add the official F-Droid client also has this slowdown, but Aurora Droid doesn't – both versions using their respective privileged extension.

**Comment by thornySoap** [comment]
I still get a freeze when having "Root Session Installer" enabled. Is this intended? Sorry, I have no idea what "Session" means in that context.
