### ISSUE TITLE
Button at a wrong place

### ISSUE THREAD

**Issue by Nang7763** [NeoApplications/Neo-Store#453]
Hi, I am actually on a wiko Y61 which has a ratio: 480px 960px
And the neo store's version 0.9.15
The button to switch about security vulnerabilities update is clickable but not entirely visible
(Sorry for those many edit)
![Screenshot_neostore](https://user-images.githubusercontent.com/112281419/223572967-0e954d8b-cfc2-441c-8dff-3ae42402a162.png)

**Comment by machiav3lli** [comment]
Yeah, I usually test on low dpis but not that extreme. Will be fixed in the next release
