### ISSUE TITLE
"Battery Optimization" screen does not go away

### ISSUE THREAD

**Issue by xdevs23** [NeoApplications/Neo-Store#458]
When I start the app, I see following screen:

![image](https://user-images.githubusercontent.com/6959245/229380522-be26ca54-57fd-4934-a958-c5a90a4830db.png)

I can close the app, force close it, but the message never goes away.
Yes, I can tap on it and do what it says, but the user should not be forced to do this!
The app works fine for my use case on my device without doing this.

**Comment by machiav3lli** [comment]
Duplicate #440
