### ISSUE TITLE
Added Total Commander Repository has no apps

### ISSUE THREAD

**Issue by Offerel** [NeoApplications/Neo-Store#471]
I have added the Total Commander repositorys (
[fdroidrepos://raw.githubusercontent.com/chrisgch/tca/master/fdroid/repo?fingerprint=3576596CECDD70488D61CFD90799A49B7FFD26A81A8FEF1BADEC88D069FA72C1 ](url) 

[fdroidrepos://raw.githubusercontent.com/chrisgch/tcabeta/master/fdroid/repo?fingerprint=7F1E1DC03B47BE5AE0C4D977B93B4137FA1149EAB8A562CA0EBC2764844113DE](url)

but i cant see the apps from this repository. Any idea why?

**Comment by machiav3lli** [comment]
Duplicate #385

**Comment by nweddle** [comment]
#385 is 404'ing for me, I am experiencing this same behavior and I was looking forward to any guidance that may have been within that issue.

#428 also refers to the same behavior.

**Comment by machiav3lli** [comment]
@nweddle #385 seems to have "magically vanished" (maybe the user removed all his/her contributions/data on GH). I'll reopen this as a replacement for now.
