### ISSUE TITLE
Issue with signature verification

### ISSUE THREAD

**Issue by p1gp1g** [NeoApplications/Neo-Store#489]
I have installed NewPipe from their upstream repo. These builds are signed with their own key (obviously). Builds on the main F-Droid repo are signed with F-Droid's keys.

If I navigate to NewPipe with Neo Store, F-Droid's builds are displayed as compatible. And it is shown as installed from both repositories (like #261)

Neo Store version: v0.9.15

**Comment by machiav3lli** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12842#note_1358460735

**Comment by p1gp1g** [comment]
Thanks, I didn't it :)
