### ISSUE TITLE
Hide installed apps

### ISSUE THREAD

**Issue by W1zardK1ng** [NeoApplications/Neo-Store#491]
I have many apps installed from Google play store and the which are also available in the fdroid store.
Now the installed section on my neo store app is a mess, it shows the apps installed from playstore and neo store.
I have enabled the ignore all new versions option but it will be nice if we can hide the apps from installed section,
so we can see only the apps which we need to see in neo store.

**Comment by machiav3lli** [comment]
duplicate #262
