### ISSUE TITLE
Crash when tapping update notification 

### ISSUE THREAD

**Issue by jont4** [NeoApplications/Neo-Store#497]
Neostore 1.0.0-alpha5 crashes when I tap the updates notification.

LineageOS 20 Android 13

Here the logs:

`ActivityTaskManager: Displayed com.machiav3lli.fdroid/.ui.activities.MainActivityX: +621ms
07-27 16:11:33.409  4820  4820 E AndroidRuntime: FATAL EXCEPTION: main
07-27 16:11:33.409  4820  4820 E AndroidRuntime: Process: com.machiav3lli.fdroid, PID: 4820
07-27 16:11:33.409  4820  4820 E AndroidRuntime: java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/main_installed } cannot be found in the navigation graph NavGraph(0x0) startDestination={ComposeNavigator$Destination(0x9ddfb08b) route=main_permissions}
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at androidx.navigation.NavController.navigate$default(SourceFile:117)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at com.machiav3lli.fdroid.ui.activities.MainActivityX.handleSpecialIntent(SourceFile:14)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at com.machiav3lli.fdroid.ui.activities.MainActivityX.handleIntent(Unknown Source:72)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at com.machiav3lli.fdroid.ui.activities.MainActivityX$onCreate$1$1$6$1.invokeSuspend(SourceFile:27)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:15)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
07-27 16:11:33.409  4820  4820 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@5c5d8f1, androidx.compose.runtime.BroadcastFrameClock@8bcfcd6, StandaloneCoroutine{Cancelling}@1050b57, AndroidUiDispatcher@4e48644]
07-27 16:11:33.412  1685  2278 W ActivityTaskManager:   Force finishing activity com.machiav3lli.fdroid/.ui.activities.MainActivityX`

**Comment by jont4** [comment]
ChatGPT about this bug:

The error log indicates that the navigation destination for the tapped notification cannot be found in the app's navigation graph. To resolve this issue, you should check the navigation graph in your Kotlin Android app and ensure that it includes the destination matching the URI provided in the error log: `android-app://androidx.navigation/main_installed`.

If this destination is not present, you may need to add it to the navigation graph or modify the URI to match an existing destination. Also, ensure that the destination has a corresponding Fragment or Activity associated with it, so the app knows where to navigate when the notification is tapped.

If you're using the Navigation component, verify that the navigation XML files are correctly configured. Double-check the destination IDs and routes to ensure they match the URI.

Once you make the necessary adjustments, rebuild the app and test it to confirm that the issue has been resolved.

**Comment by machiav3lli** [comment]
Test build bugs are exclusively discussed in the groups! They're distributed and discussed only there to avoid such mess here! The issue is already known and will be solved by next test build.

**Comment by jont4** [comment]
oh... sorry. I didn't really know.
