### ISSUE TITLE
Droid-ify crashes when attempting to sync repositories

### ISSUE THREAD

**Issue by sphars** [NeoApplications/Neo-Store#50]
Just factory reset my Pixel 4a to Android 12 (released today). Installed v0.3.1 of Droid-ify. Tried to sync the repositories, as no apps were shown as available for downloading. Droid-ify immediately crashed. Only default repos were setup. Here's a screen recording of it: [https://giant.gfycat.com/BeautifulClearBagworm.webm](https://giant.gfycat.com/BeautifulClearBagworm.webm) 

Let me know if I can help further.

**Comment by spncrhrstn** [comment]
Thanks, I saw that issue, but since it was just about adding new repositories, not syncing existing one, I didn't think it was the same issue.

Will look out for the next release.
