### ISSUE TITLE
Phrasing of tracker details

### ISSUE THREAD

**Issue by IzzySoft** [NeoApplications/Neo-Store#501]
Now that more and more F-Droid apps have been scanned by Exodus, I notice more and more entries with a "pure green" marker in that section. On the details page it then says: "No tracker details to show" – which is a bit ambiguous: Does it mean "no trackers found", or just that there were trackers found but details cannot be shown for some other reason? Maybe the phrasing could be a little more clear, like "no trackers found" (if there are scan results saying so), and "xx trackers found but we have no details on them" otherwise?

That said, Exodus only covers apps from F-Droid.org, but not from 3rd party repositories. At least with my repo, there would be the possibility of using the results from my scanner. I could provide you with the corresponding SQLite database file (which could be pulled the same way as the index itself) if you're interested. Not sure how it could be handled for other 3rd party repositories, but am afraid for those there won't be any (easy) way – except maybe scanning them on-device using my library definitions, which are also openly available (IIRC you've already used them). Could be an idea to initialize such a scan manually on request for apps installed on-device which do not have those details.

**Comment by machiav3lli** [comment]
When Exodus provides a response and this is saved in the DB, this would be translated to an data-exists state, based on which the indicator will show a result, if no response is saved it'll show an indicator that there's no data available about the app's trackers. The trackers and keys come both from Exodus, so such that there's no middle ground e.g. an app includes tracker keys but no info on those.

 As we wrote privately; This is one of the reasons why I still don't filter the source. Adding a scanning script (or one that send those to Exodus to scan) may be a solution, but am surely open to brainstorming simpler less resource-intensive solutions to improve on this (maybe in collaboration with the Exodus and F-Droid-Backend communities).

**Comment by machiav3lli** [comment]
## For comparasion

### No Exodus data:

![Screenshot_20230817-230926](https://github.com/NeoApplications/Neo-Store/assets/40302595/fcb1797e-11af-428d-858c-4a05fc05700e)

### No trackers in Exodus data:

![Screenshot_20230817-231037](https://github.com/NeoApplications/Neo-Store/assets/40302595/538d1db1-bee9-423b-a089-3028ca30d4df)

**Comment by IzzySoft** [comment]
Thanks – and yes, it's the second example I referred to. The indicator says "few to none", and in the details it says "nothing to show" – which still does not clarify if that's due to "none", or "few but we don't know which or what to show". So preferably it would differentiate between "there are no trackers" and "there are {number} trackers but we have no details". If the indicator shows "few to none", you must have some information on that – else it couldn't even state that :wink:

(the Exodus response either has no `results` element and thus no information (which probably would mean your first example), an empty `results` elements meaning "no trackers found" – or a `results` element with details on the trackers it detected, so it should be possible to differentiate)

**Comment by machiav3lli** [comment]
Should be fixed in 47806aa0

**Comment by IzzySoft** [comment]
> No trackers to show

So there are trackers which cannot be shown? :thinking: Wouldn't something like "This app has no known trackers" more suitable?

**Comment by machiav3lli** [comment]
Actually the commit changes it to "no trackers" when exodus data is available, otherwise "no data on trackers available"

**Comment by IzzySoft** [comment]
Ah, shame on me – I've read it the wrong way… :see_no_evil: Thanks!
