### ISSUE TITLE
The category list is vertical, not horizontal

### ISSUE THREAD

**Issue by blacklightpy** [NeoApplications/Neo-Store#502]
For a while I thought this was a bad UI design choice, but then I saw the screenshots on the repo and it looks normal here. Please fix this.

My device: POCO M4 Pro 4G (fleur)
Android version: Android 12

![Screenshot_2023-08-14-18-42-55-254_com.machiav3lli.fdroid.jpg](https://github.com/NeoApplications/Neo-Store/assets/28739146/5644dd3c-67a7-46aa-b528-e1b7aef38de5)

**Comment by Deigue** [comment]
Or to be less extremist, offer both options/variations, via an option in the settings menu.

**Comment by machiav3lli** [comment]
It's meant to be vertical, community survey when devloping the version then was something like 50-50. That said, with 1.0.0 this shouldn't be a real issue anymore.
