### ISSUE TITLE
[BUG] Use the decriptions translations of the app

### ISSUE THREAD

**Issue by LaBaude32** [NeoApplications/Neo-Store#504]
Hi dev !
First of all, thank you for your magnificent work.
I published an app on fdroid and realized that the translations of the app descriptions are not used in Neo-Store. Nor in the list of version changes.
Here's a comparison between Fdroid and Neo-Store:
![Screenshot_20230816_162651_F-Droid](https://github.com/NeoApplications/Neo-Store/assets/42806696/c3177f70-3f21-42c5-91aa-9e998d8627c1)
![Screenshot_20230816_162727_Neo Store](https://github.com/NeoApplications/Neo-Store/assets/42806696/497a04e9-d158-49b7-95a9-75224e1db64f)

I wanted to report this bug. 
Thanks a lot!

**Comment by machiav3lli** [comment]
Already added to 1.0.0 (alpha builds available in the community groups)
