### ISSUE TITLE
Theme: dynamic (black)

### ISSUE THREAD

**Issue by ksvijay1** [NeoApplications/Neo-Store#506]
It would be nice if the amoled(black) theme has dynamic colour.

**Comment by Cyanide-1** [comment]
i second this, this would be good to add

**Comment by machiav3lli** [comment]
Actually I left this for the system to handle, most A12+ ROMs provide support for system 0-black background, nevertheless maybe I'll add an option to enforce 0-black, for those who doesn't…

**Comment by Cyanide-1** [comment]
yeah sounds like a good call, appreciate it!

**Comment by machiav3lli** [comment]
Covered in 000d6b6f7d6f887e563096f2f6f84f99cfd38a85

**Comment by Cyanide-1** [comment]
thanks :3
