### ISSUE TITLE
[FR] UX: add visual feedback when search in in progress

### ISSUE THREAD

**Issue by breversa** [NeoApplications/Neo-Store#512]
Hello! :)

As searching is still pretty slow, it would be useful to display a "search in progress" until the search (in the Explore tab) is done.

Currently, I’m still unsure is the search is going on or not.

Some kind of rotating spinner (similar to the sync one) would be a great start, but a progress bar (with "X apps searched out of Y", maybe?) would be awesome. :)

**Comment by machiav3lli** [comment]
Technically with the current backend there's no real possibility for an indicator (X out of Y). On the UX side of things, the current v1.0.0 test builds already fixes the issue.
