### ISSUE TITLE
Update date on downloads

### ISSUE THREAD

**Issue by fusionneur** [NeoApplications/Neo-Store#513]
Curently download button on on installed tab only shows an ordered list of updates, but having some timestamps on each entry might prove more useful

**Comment by machiav3lli** [comment]
Here's an interesting question: should it be the time of install or start of download?

**Comment by machiav3lli** [comment]
Ah, I thought you're already on 1.0.0-alpha… here's how it looks like there (fixing all the UX related issues):
![Screenshot_20230905-171553](https://github.com/NeoApplications/Neo-Store/assets/40302595/2ffd3b5a-d1e3-4d02-bf78-201090c3e306)

It's thought of as a log for downloads, where the user may monitor the currently downloading apps and see the download history (cause most of downloads happen in the background), so you always have an overview on what has been installed or updated…
