### ISSUE TITLE
Tabs on top like the screenshots?

### ISSUE THREAD

**Issue by rmlrml** [NeoApplications/Neo-Store#515]
Hello.  In Neo Store my category tabs are along the left side, instead of along the top like in the screenshots, and the text is sideways.  I don't see an option anywhere in settings to change it to on top.  How do I change it to make the tabs on top like in the screenshots?  Thanks

**Comment by machiav3lli** [comment]
The screenshots are old, the vertical is the only one supported, but it should be less annoying with the new categories page coming in v1.0.0 (screenshots are from alpha06)
![Screenshot_20230905-015933](https://github.com/NeoApplications/Neo-Store/assets/40302595/756cb902-3480-429e-99dc-f40d3ece5405)
![Screenshot_20230905-015943](https://github.com/NeoApplications/Neo-Store/assets/40302595/1658a49b-5557-4624-9cd1-a218d9169875)
