### ISSUE TITLE
List of context menu is vertical

### ISSUE THREAD

**Issue by victorfernandesraton** [NeoApplications/Neo-Store#520]
I have a issue in Sansung A34 5G (SMA346M/DSN) in search context the secomdary categories is in vertical instad of horizontal, as you can see above

![Screenshot_20230930_105109_Neo Store](https://github.com/NeoApplications/Neo-Store/assets/43411882/489a5977-4440-4787-9775-192da8a8d3a1)

**Comment by machiav3lli** [comment]
It's not a bug, but was designed to be like this. But the design has already been changed in latest 1.0.0 test builds
