### ISSUE TITLE
Improving the sorting & filters page design and making it structured

### ISSUE THREAD

**Issue by bhaskarblur** [NeoApplications/Neo-Store#521]
Hi there, i am new here and wanted to contribute to this amazing project, i saw that the filters page design isnt structured and goes out of the flow than rest of the app, so i thought to redesign it and here's a mockup of the redesign.

I would like to develop it in code as well, if you find this valid it please assign me to do this task.
Thanks

I am attaching below the before and after( left - right respectively)

Before:
![WhatsApp Image 2023-10-01 at 8 21 27 PM](https://github.com/NeoApplications/Neo-Store/assets/85757758/b7b8bc03-0b42-47ab-801e-78812c67563d)

After:
![filters redesign](https://github.com/NeoApplications/Neo-Store/assets/85757758/442cb92e-6742-4854-a48e-f1855fc5f010)

**Comment by bhaskarblur** [comment]
Please see and if approved assign me, Thank you!

**Comment by bhaskarblur** [comment]
@machiav3lli Please have a look.

**Comment by bhaskarblur** [comment]
@machiav3lli any reviews?

**Comment by machiav3lli** [comment]
PS: @bhaskarblur I don't know if and what experiences you've made in FOSS, but patient is the essence as most of people involved in FOSS do this voluntarily

You're unfortunately referring to an old UI, the current UI in 1.0.0-alpha07 looks like this:

![Screenshot_20231013-014229](https://github.com/NeoApplications/Neo-Store/assets/40302595/96e816f8-c63f-4c77-a2a8-111499d0556b)

**Comment by bhaskarblur** [comment]
Hi @machiav3lli . Ok I guess I should find a better place to improve things in the app.
