### ISSUE TITLE
Potential invalid requests resulting in server DoS

### ISSUE THREAD

**Issue by SkewedZeppelin** [NeoApplications/Neo-Store#522]
**Describe the bug**
I run the divestos.org F-Droid repositories, my server logs are  filled with invalid requests for the resource `/fdroid/official/null` with the User-Agent okhttp/5.0.0-alpha.11.
This is the same version as declared here: https://github.com/NeoApplications/Neo-Store/blob/master/build.gradle.kts#L21

**To Reproduce**
1. Enable a DivestOS repo(, and probably any other repo)
2. Swipe between screens
3. Watch invalid requests be made

**Expected behavior**
Not make such invalid requests

**Additional information**
I am not entirely clear if this is actually Neo-Store, it may be Droid-ify, as they previously used the same okhttp version: https://github.com/Droid-ify/client/commit/1eb40c3e167f60ca48198588d0172edfeedceb71#diff-df8b4af8cccf28e19228317a74d3fba23fed6c067665f72670b7d4986515ad39L104
https://github.com/Droid-ify/client/issues/499

Please also consider declaring your User-Agent as well.

**Comment by machiav3lli** [comment]
Is this still existing or was it only on Droidify's side? Calls from latest beta should also include a clear UA.

**Comment by SkewedZeppelin** [comment]
I'm still seeing about 200 of these requests per hour, but we can close this.

> include a clear UA.

thanks!

**Comment by machiav3lli** [comment]
And please report back should you see the UA (package name and version) on these requests.
