### ISSUE TITLE
Add animation on the navigation bar items when switching pages. 

### ISSUE THREAD

**Issue by TeaOwO** [NeoApplications/Neo-Store#523]
Title says it all.

**Comment by machiav3lli** [comment]
I guess people's patient is pretty limited :stuck_out_tongue_winking_eye:

**Comment by TeaOwO** [comment]
> I guess people's patient is pretty limited :stuck_out_tongue_winking_eye: 
Sorry, I am a really impatient person ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
