### ISSUE TITLE
Error when building.

### ISSUE THREAD

**Issue by TeaOwO** [NeoApplications/Neo-Store#525]
> Task :kspDebugKotlin FAILED
e: [ksp] C:/Users/hello/Neo-Store/src/main/kotlin/com/machiav3lli/fdroid/database/DatabaseX.kt:127:
            AutoMigration Failure: Please declare an interface extending 'AutoMigrationSpec',
            and annotate with the @RenameTable or @DeleteTable annotation to specify the change
            to be performed:
            1) RENAME:
                @RenameTable.Entries(
                    @RenameTable(
                        fromTableName = "temporary_release",
                        toTableName = <NEW_TABLE_NAME>
                    )
                )
            2) DELETE:
                @DeleteTable.Entries(
                    @DeleteTable(
                        tableName = "temporary_release"
                    )
                )

w: [ksp] No module found for 'com.machiav3lli.fdroid.service.worker.ExodusWorker'. Definition is added to 'defaultModule'
e: Error occurred in KSP, check log for detail

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kspDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
26 actionable tasks: 1 executed, 25 up-to-date

**Comment by machiav3lli** [comment]
I guess some WIP got through to the scheme :sweat_smile:
