### ISSUE TITLE
Integrate F-Droid Nearby

### ISSUE THREAD

**Issue by RageGamerBoi** [NeoApplications/Neo-Store#530]
The default F-Droid app has F-Droid Nearby integrated to aid in offline app distribution.

It would be really nice to have in Neo Store, not because it’s entirely necessary (though it can be really handy), but because when you need it and don’t have it there aren’t really any other viable alternatives.

I really don’t want to have to install F-Droid or the (very outdated) dedicated F-Droid Nearby app as well as Neo Store.

**Comment by AkashKrx** [comment]
@RageGamerBoi you can try local send. It's an alternative to AirDrop. https://github.com/localsend/localsend

**Comment by RageGamerBoi** [comment]
That's a solution for one of F-Droid Nearby's usecases, but not really what I was looking for...

I was talking about adding this specifically to Neo-Store somehow:
https://gitlab.com/fdroid/fdroid-nearby

**Comment by machiav3lli** [comment]
Not planned. There's enough FOSS apps that fulfill these functions.
