### ISSUE TITLE
Replace Bromite repo with Cromite

### ISSUE THREAD

**Issue by dmint789** [NeoApplications/Neo-Store#542]
Bromite hasn't been maintained since 2022, so it's a security risk to show people they can add this repo and install this browser. Cromite is the new fork of Bromite, so I think the Bromite repo in the default list of available repos should be replaced with the Cromite one: https://www.cromite.org/fdroid/repo/?fingerprint=49F37E74DEE483DCA2B991334FB5A0200787430D0B5F9A783DD5F13695E9517B

**Comment by machiav3lli** [comment]
Already added in bf3441660834d25bb90cb925b21f523feb53b7d1
