### ISSUE TITLE
Neo Store handles "ast" locale very badly

### ISSUE THREAD

**Issue by enolp** [NeoApplications/Neo-Store#547]
Hi,

Neo Store thinks "ast" locale (ISO 639-2) is the same as "as" locale (ISO 639-1) which is very wrong. "ast" locale refers to Asturian language and "as" locale refers to Assamese language. Also, on first run, Neo Store shows all dialogs in English when "ast" locale is set on the device unless you explicitly set Asturian on Neo Store settings.

**Comment by enolp** [comment]
Still present on version 1.0.0-beta3

**Comment by machiav3lli** [comment]
Yup, will be fixed when in release-candidate state
