### ISSUE TITLE
Provide more app info

### ISSUE THREAD

**Issue by dhishkyaon** [NeoApplications/Neo-Store#55]
It will be great if the client can provide more info about the application if available. Something like this 👇🏾

![58D3970C-4076-42DD-99D0-D1BA8DB618C8.jpg](https://user-images.githubusercontent.com/88529066/138123929-763c9ee9-aa2c-47e4-9ed9-57f24d689f6f.jpg)

**Comment by Iamlooker** [comment]
![Screenshot_20211021-201851611](https://user-images.githubusercontent.com/60404093/138302611-8b819a52-f373-4b15-851c-9e83777e96d6.jpg)

Howz this?

**Comment by dhishkyaon** [comment]
@Iamlooker i agree with you. Repos are already listed down there and they are too long.
