### ISSUE TITLE
Update button only works the second time it is pressed

### ISSUE THREAD

**Issue by KnockoffFeline** [NeoApplications/Neo-Store#550]
**Describe the bug**
When viewing an app, the update button does nothing when pressing it for the first time. Only after the second time, it actually responds and I get prompted to install the update.

**To Reproduce**

1. View an app that has an update available in Neo Store
2. Tap 'Update'
3. Nothing happens
4. Tap 'Update' again
5. Actually get prompted by the Package Installer to update the app

**Expected behavior**
The 'Update' button would work for the first time it is pressed.

**Smartphone:**

- Device: Redmi Note 11 Pro 5G
- OS: Android 13
- Version: 0.9.15

**Comment by jont4** [comment]
You've already tested the version 1.0.0 beta2?

**Comment by KnockoffFeline** [comment]
No, I haven't yet. Where can I get it?

**Comment by jont4** [comment]
> No, I haven't yet. Where can I get it?

On Neo's channel: https://t.me/neo_applications/373

**Comment by KnockoffFeline** [comment]
The issue is now fixed on that version. Thanks!

**Comment by machiav3lli** [comment]
Should be fixed in 1.0.0
