### ISSUE TITLE
App list has too long load time

### ISSUE THREAD

**Issue by Baerbeisser** [NeoApplications/Neo-Store#553]
While the app list  (category "discover") needs about a second to load on my OnePlus 9 upon opening the app, it is about half a minute on my slow but not underpowered E-Ink tablet Onyx Leaf 2 (4-core, 2 GHz,2  GB RAM). This is too long.
Since both are on the same fast Wifi, i guess it has to do with processing the repo list.
Any way to speed that up?
And please add a placeholder text, like "Loading Repo list" or something.

**Comment by machiav3lli** [comment]
Duplicate #237
