### ISSUE TITLE
[Feature request] Open IzzyOnDroid links

### ISSUE THREAD

**Issue by KaKi87** [NeoApplications/Neo-Store#559]
Hello,

Neo Store can currently only open links from F-Droid (f-droid.org and subdomains).

It would be nice for it to be able to open links from IzzyOnDroid (apt.izzysoft.de/fdroid/) as well.

Thanks

**Comment by machiav3lli** [comment]
Already implemented test latest 1.0.0-beta03

**Comment by KaKi87** [comment]
> test latest 1.0.0-beta03

Where, please ?

**Comment by machiav3lli** [comment]
In the community groups either on [Telegram](https://t.me/neo_android_store) or [Matrix](https://matrix.to/#/#neo-store:matrix.org)

**Comment by KaKi87** [comment]
Would it be possible to upload these at least on GitHub so that I could download these using Obtainium ? Thanks

**Comment by machiav3lli** [comment]
Sorry but not happening. I prefer to keep test builds and reporting in the community groups as communication is less limited and avoiding spammy/ambiguous reporting on GH/GL

**Comment by KaKi87** [comment]
Well, I'd like to be understanding, but it would be easier if you'd make minor releases more regularly, because this is the 2nd feature which has already been implemented since who knows when yet that I'll be waiting for, the 1st one being #106 since 5 months ago...

**Comment by machiav3lli** [comment]
Was already the situation with 0.9.X, but the jump to v1.0.0 is huge, so it takes time (considering also private life factors in the equation)

**Comment by KaKi87** [comment]
> Was already the situation with 0.9.X, but the jump to v1.0.0 is huge

Which is why I specifically mentioned *minor* releases, both features I mentioned could have been released without a major increment.

> considering also private life factors in the equation

That, I understand.

**Comment by machiav3lli** [comment]
I think there's also hundreds of features requested from other users that would've been released without a major increment. So I don't see any reason to do extra work to release sub-releases with those two features or others. 

If someone is really interested, then he/she could maybe contribute the hours needed to do so.

**Comment by machiav3lli** [comment]
I think you're ignoring the main point: resources.

You can gladly theorize this all, but considering the rebasing happend since 0.9.15, it's not a small change to implement this or that feature (not to mention the considerstion, what should be included in small increments and what not) and I wouldn't spend my FOSS time duplicating my work over and over.
