### ISSUE TITLE
Unable to get past battery optimization and permission to post notifications 

### ISSUE THREAD

**Issue by IntelligentFunction** [NeoApplications/Neo-Store#560]
I just installed the latest version of this, but I can't get past the above screen. I can  tap on the settings and look through them, but nothing allows me to get to the actual apps to download. How do you get past this or is this an actual bug?

**Comment by machiav3lli** [comment]
Did you press teh sync button (the rotating arrows)?

**Comment by IntelligentFunction** [comment]
Hi, thanks for your reply, yes I did that, it turns out you have to allow notifications.  I don't want my phone alerting me for anything at all so I naturally opted for don't allow. 
I uninstalled it, reinstalled it and allowed notifications and then it all came to life. thank you  this is now solved.
