### ISSUE TITLE
microG Services Core cannot be updated due to different signature

### ISSUE THREAD

**Issue by lss4** [NeoApplications/Neo-Store#564]
ROM: LMODroid 4.2 (Android 13)
Neo Store: 0.9.15

Context:
microG Services Core installed using [this module](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases) since it has variants that offer exactly the features I need. As of the latest officially released module version (`2.12.0`), it comes with microG version `0.2.28.231657`.

Problem:
Neo Store suggests an older version of microG (`0.2.27.233616` to be precise) and reports recent versions (`0.3.0.233515` at the time of writing) as incompatible due to having different certificates, preventing update.

However, official F-Droid client can update microG (installed per Context) just fine.

For both clients, I'm trying to update microG Services Core from microG's official F-Droid repo. Not sure if it's related to the old issue #131 which is still open.

**Comment by machiav3lli** [comment]
Try disabling signature check in the 1.0.0 and report back please.

**Comment by lss4** [comment]
> Try disabling signature check in the 1.0.0 and report back please.

Just tested the new version of Neo Store and successfully updated microG after disabling signature check.

LGTM. Closing the issue.

**Comment by RealStickman** [comment]
Hey, I also ran into this issue just today.  
What exactly is the impact of disabling signature checking?  
Would it be better to only enable this for microg apps or on a per-repo basis?

**Comment by machiav3lli** [comment]
@RealStickman If your question is about NS then you'll be allowed to download packages that are not compatible with your installed ones. If you mean on the system side (using a xposed module): could be called at least a security issue, as your system would allow installing packages from devices and sources that may not relate to the original developer.

**Comment by lss4** [comment]
It appears I still have to toggle signature check whenever I try updating microG.

So far only Neo Store complained about it. It has always been possible for me to update microG through other means, like using official F-Droid client with their repo, as well as directly sideloading the APK from official GitHub releases.

PS: Looks like [this question](https://github.com/microg/GmsCore/issues/1932) on the microG side might be relevant. Maybe there indeed were some extra work done in the repo to take signature spoofing into consideration.
