### ISSUE TITLE
Support opening Izzy on Droid links

### ISSUE THREAD

**Issue by j-lakeman** [NeoApplications/Neo-Store#570]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I manually have to copy and paste app names that are only available from Izzy's repository instead of just clicking on the URL.

**Describe the solution you'd like**
Either enable Izzy on Droid links by default to be supported in Android app settings or make it optional.

**Comment by machiav3lli** [comment]
Already added in the 1.0.0 test builds and seen multiple duplicate issues.

In the future please check the issues (also closed ones), for similar issues before opening a new one.
