### ISSUE TITLE
Fix issues with installing apps and updates

### ISSUE THREAD

**Issue by git10700** [NeoApplications/Neo-Store#577]
Installing apps and updates is super buggy:
- sometimes it shows that it's installing while it is not installing.
- a lot of times it shows that it's downloading while making the whole app freeze, which presists even after terminating the app, then reopening it.

Tested in latest beta from telegram and latest f-droid release.

Android 13 and 14.

**Comment by machiav3lli** [comment]
Test release issues and bugs are discussed mainly in the community groups to avoid spamming GH/GL

**Comment by HyperCriSiS** [comment]
I also have this issue in the official release.
