### ISSUE TITLE
Request: Installer

### ISSUE THREAD

**Issue by cikgit** [NeoApplications/Neo-Store#581]
Hi, can you make an option for App Manager to install apps?

https://muntashirakon.github.io/AppManager/

**Comment by machiav3lli** [comment]
Already available in the test builds from months (only available in the community groups on Telegram and Matrix).

**Comment by cikgit** [comment]
> Already available in the test builds from months (only available in the community groups on Telegram and Matrix).

Thank you so much. I didn't know that. This function is on mainstream version right now and crucial for me.
