### ISSUE TITLE
1.0-rc2 - old download attempts are stuck in the UI

### ISSUE THREAD

**Issue by yoshimo** [NeoApplications/Neo-Store#584]
Even if a more recent version is already downloaded and installed, I still see older versions as partially downloaded. These items never progress and never abort. 
![Screenshot_2024-04-23-20-58-18-690_com machiav3lli fdroid](https://github.com/NeoApplications/Neo-Store/assets/17909/546ac6b3-bdb7-4142-b159-535e2ec60369)

**Comment by machiav3lli** [comment]
You can remove them from the downloads tab (there's an icon for this)

**Comment by yoshimo** [comment]
Yea but doesn't it mean something went wrong in the first place that neo couldn't recover from?

**Comment by machiav3lli** [comment]
You didn't provide the whole story so I can't really judge if something went wrong or it's just an older issue from earlier test builds that was kept after updating.

A clean install of the stable 1.0.0 release less than an hour ago would be the suggested way to go. Furthermore issue reports on test builds are only allowed in the community groups (noise reduction on GH/GL)
