### ISSUE TITLE
Screenshot not loading

### ISSUE THREAD

**Issue by stinglama** [NeoApplications/Neo-Store#59]
The clicked screenshot does not load, other screenshots load perfectly fine. Here is a small video showing that issue.

https://user-images.githubusercontent.com/89147103/138206092-9e91b5f1-71cb-4521-84f8-0b1c18864819.mp4

**Comment by mamasch19** [comment]
Had the same problem today with 0.3.6

**Comment by Iamlooker** [comment]
Server issue
