### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by obfusk** [NeoApplications/Neo-Store#590]
Hi! The Neo Store 1.0.0 APK is *almost* [reproducible](https://reproducible-builds.org/)... except for an [embedded list of locales being non-deterministically ordered](https://github.com/NeoApplications/Neo-Store/blob/master/build.gradle.kts#L233).

This is the [exact same issue that Droid-ify had](https://github.com/Droid-ify/client/issues/674), and was [easy to fix by just sorting the list](https://github.com/Droid-ify/client/pull/675/files).

cc @IzzySoft

**Comment by obfusk** [comment]
So... this fixed the locales issue, as expected. Thanks!

However... compared to my build from the `1.0.1` tag, the APK attached to the release has a different embedded commit hash and included the `META-INF/**.version` files which should have been excluded.

The former would be [this issue](https://github.com/CatimaLoyalty/Android/pull/1781), the latter is presumably because [this bit in `build.gradle.kts`](https://github.com/NeoApplications/Neo-Store/blob/1.0.1/build.gradle.kts#L135) was commented out during the build of the APK attached to the release.

The good news is that I was able to build an identical APK with just these two small workarounds now, so it is RB :)

```sh
git reset --soft b8367fa8ea81a5c56cec46c7ec5c1883a5e13037
sed -r '/META-INF.*version/d' -i build.gradle.kts
```

**Comment by machiav3lli** [comment]
@obfusk  Exactly! I actually recalled both points while the building was going on, but didn't have the time (and the mood) to rebuild it just for the sake of being RB :D But I'll write that down for my future workflow, thanks for the note!

**Comment by obfusk** [comment]
This time the tag `1.0.2` points to commit abae89112dab359632b9dd89be27a4f36788731b but the APK was built from 61538e52f849683fdfee2370da695e1d1a7a7005 (the only difference being the changelog so it's just the embedded commit hash that's an issue and if I `git checkout 61538e52f849683fdfee2370da695e1d1a7a7005` I do get the same APK) :sweat_smile:

**Comment by machiav3lli** [comment]
@obfusk Yup! This time I forgot to add the metadata changelog, and amended the commit after the build. Was in hurry on my way to the carnival :dancing_men:

**Comment by Frmd-git** [comment]
> [@obfusk](https://github.com/obfusk) Yup! This time I forgot to add the metadata changelog, and amended the commit after the build. Was in hurry on my way to the carnival 👯‍♂️

Is NeoStore no reproducible build any more?

**Comment by IzzySoft** [comment]
@Frmd-git why not? The latest release was just confirmed RB at IzzyOnDroid.

**Comment by Frmd-git** [comment]
When the app was updated (2 days ago), the green symbol inside Neostore was missing.
Now it's there; not sure if it was a caching or a different type of error.
But it's fine now.

**Comment by IzzySoft** [comment]
> When the app was updated (2 days ago), the green symbol inside Neostore was missing.

RB happens on a separate track here, so the shield can be delayed by a few hours.
