### ISSUE TITLE
App not listed in Neo but in F-Droid

### ISSUE THREAD

**Issue by Nordlicht-13** [NeoApplications/Neo-Store#598]
I was looking for a app on the Neo-Store but it's not listed. When I search for "Kaffee" in F-Droid, the app is listed. 
This is the link to the app:
https://www.f-droid.org/de/packages/com.github.muellerma.coffee/

**Comment by machiav3lli** [comment]
Are you already on 1.0.1 or still on older versions? Cause I can see here (1.0.1)

**Comment by Nordlicht-13** [comment]
I'm on 1.01 running GraphenOS.
I can't find it, but when it's installed, it's listed under installed apps.

**Comment by machiav3lli** [comment]
Ah, I guess you have the 1000 apps search limitation, change that in the personal settings to 2000+ or 0 (all apps). This was introduced in 1.0.1 to accelerate loading the apps list on search, as it was a reported pain point for some users.

**Comment by machiav3lli** [comment]
Also, I think NS should be restarted or one of the search filters should be changed and then undo for the number to be considered (a bug, will be fixed in next point release)

**Comment by Nordlicht-13** [comment]
Yes, with 2000 it's working after restarting the store.
Thanks for helping.

**Comment by Incog5** [comment]
Was experiencing the same bug, a number or apps not coming up in search. 
Changing the setting to 2000 fixed it.

**Comment by Incog5** [comment]
2000 wasn't enough and still couldn't find some apps. Changed to zero, it's slow to load but works better.
