### ISSUE TITLE
[Feature request] bring back search bar in “installed” tab

### ISSUE THREAD

**Issue by j-lakeman** [NeoApplications/Neo-Store#604]
I'm pretty sure prior to the last major update it was possible to perform an offline search though installed apps. That seems not possible anymore, but was quite handy for quickly filtering the installed apps IMHO.

**Comment by machiav3lli** [comment]
It'll cause some headache concerning UX, but I'll see when its time comes

**Comment by j-lakeman** [comment]
I mean only searching _installed_ apps in the _installed_ tab

**Comment by machiav3lli** [comment]
@opusforlife2 all types of search are offline (the data is read on sync and stored locally). What I meant was adding a search bar specifically for installed apps…

**Comment by j-lakeman** [comment]
Or maybe through “sort and filter” as it's rather filtering than searching :thinking:

**Comment by GfEW** [comment]
> tab-specific search as opposed to a repo-wide search, instead of offline and online.

Auto-adapting the filtering/sorting of search results in each tab appropriately would make a lot of sense: 

1. Latest: search in the list of latest apps (pre-sorted by recency?)
2. Explore: search in the list of "explorable" apps (i. e. everything)
3. Installed: search in the list of installed apps
4. Downloads: search in the list of downloads.

(Since the "Installed" main tab is divided in two sub-tabs, there are four tab views.)

**Comment by machiav3lli** [comment]
I would disagree on many of the assumptions, although I understand where this come from. Working on 1.0.0 the wish came from the community to have this one search page, it also make/made sense as you'd expect from a search page for all apps available in a store and not only the limited number in one page (this is mostly clear when considering the ambiguity of 1 & 2).

On the way working on 1.0.0, there was all type of different implementations for search and the current seemed the one to be most accepted by the community involved. That said, I'll reconsider things and survey the community when working on future minor/major releases, but most possibly this won't be a part of a point release.

**Comment by machiav3lli** [comment]
Actually filtering would be the more precise verb, as such search bar is just filtering an already limited group. Otherwise, I actually thought of adding fast filters to the search page UI (chips representing e.g. "all", "installed" and "new").
