### ISSUE TITLE
UI: Short descriptions of apps are a mess

### ISSUE THREAD

**Issue by axelsimon** [NeoApplications/Neo-Store#606]
Hi there,

Short descriptions of apps in the UI are a bit of a mess.
I'm talking about the description that shows under the name of an app, in the app lists (explore, latest, installed).

- they can be quite long, but don't scroll or allow to be expanded. So you can get something like the following, which leaves you knowing _nothing_ about the app:
  > Linwood Butterfly
  > Powerful, minimalistic, cross-platform, opensource not…
- they are only shown no the app lists, and not in the app page where you only get the long description. So if you're unlucky, the devs put all the useful info in the short description, there's no long description, and you still don't know what the app does.

Easy fix: just show the short description in full on an app's page between the "install" area and the screenshots.

**Comment by machiav3lli** [comment]
I think it's a knowledge gap on your side (or you're still on pre-1.0.0 version):
- Long tapping app items in the pages extends the text to full
- In the app page, the short description is placed under the screenshots, when clicking to "show more" it switches to the long description.

**Comment by axelsimon** [comment]
Thanks for your answer. I am indeed on a version before 1.0.0, I'll upgrade.

That being said, i don't think putting this on the user and down to a "knowledge gap" is correct, as an app should guide users and help them. Also, long tapping app items in the app lists does not extend the text (just tried), it just extends the item to show the heart option and "install".

There might be some confusion too, as the text shown on the app lists is clearly not the same than the one shown on an app's description, whether there is and/or you press the "Show more" button or not.

Going back to the [Linwood Butterfly example](https://f-droid.org/en/packages/dev.linwood.butterfly/):
- " Powerful, minimalistic, cross-platform, opensource note-taking app" is what I'm referring to as short description.
- "Butterfly is a note taking app where your ideas come first. You can paint, add texts, and export them easily on every device. This app works on android, windows, linux, and in the web. (…)" is what I'm referring to as long description.

**Comment by machiav3lli** [comment]
Sorry if knowledge gap seemed offensive, it's just my description of missing on certain things (taken you're already on 1.0.X). That said…
> Also, long tapping app items in the app lists does not extend the text (just tried), it just extends the item to show the heart option and "install".
I guess you're still on 0.9.X, which is again a contra to my presumption when talking on a "knowledge gap".

**Comment by machiav3lli** [comment]
> Just upgraded to the latest 1.0.1, the short description appears in full, so this issue is now moot.

Nice!
