### ISSUE TITLE
Slew of Problems when Adding a New Repository

### ISSUE THREAD

**Issue by 48-mq** [NeoApplications/Neo-Store#608]
1. When clicking the "+" sign to add a new repository by URL, the app automatically copies from the clipboard, which is unexpected and automatically pasting from the clipboard is not something I want to see in an app, for privacy reasons.

2. Then the app seems to not check the URL for validity or try to get a fingerprint, instead only asking whether to "save" or "cancel".

3. When clicking "save", the app still doesn't check the URL, nor gets a fingerprint, but it does display a barcode for some reason. What's the point of this? My eyes don't (yet) have a barcode scanner, and since I just pasted the URL myself, I can clearly read just fine.

4. The only two options shown on this page with this page below the barcode are "Delete" and "Edit". Clicking "Edit" takes one back to the page described in 1. above. There is no "back" button or other navigation aid to guide the user to the next step in the workflow.

5. Going back using the Android back button takes one to the list of repositories, which is the same as before. The new repository is not enabled by default, but is instead disabled. Why would anyone add a repository to immediately disable it?

6. The name of the new repository is always displayed as "new repository" even though this tells me nothing about the URL that was added. There's also no way to enter one's preferred name for the new repository in the workflow described in any of the previous steps. And there's no way to rename it after adding it.

**Comment by machiav3lli** [comment]
Let's address some points already:
1. It's meant as a feature to easily add a repo through copying it's link (Fingerprint is also copied when present, related to 2.).
    - Concerning privacy: the copied info goes no where except in the fields. Side note: When NS have access to this data, all your apps have also access to this data.
2. Checking for "Validity" would require the app to connect to the repo, which is nothing I'd like an app to do, before the user explicitly enables the repo. 
3. Save is not enable! And therefore there's still no checking of validity (URL, Fingerprint or whatsoever).
4. TODO add button to hide the sheet (swiping down already does this for you)
5. Hm… I guess, I and other users… anyway: TODO add an option on default behaviour
6. The name of a repository is parsed from it's data (when enabled, kept when disabled afterwards) and am not sure what is the use of overwriting the name of a repository. But I'll consider this again.

**Comment by machiav3lli** [comment]
@opusforlife2 Thanks for the comment! Yeah, I guess adding an enable button to the view sheet will cover the most use cases.
