### ISSUE TITLE
Downloads stuck

### ISSUE THREAD

**Issue by Issue-maker-9000** [NeoApplications/Neo-Store#613]
![Screenshot_20240519-213521](https://github.com/NeoApplications/Neo-Store/assets/58198453/a8bbfe77-1d15-4346-9feb-4bbaa2df9fb5)

Those 2 apps are stuck there on downloading, both of the apps are at the latest version. (Nothing to update)
Cancel download button doesn't do anything, been there since neostore 1.0 currently on 1.0.2

It is just visual but kinda annoying

**Comment by machiav3lli** [comment]
Should be possible to remove from downloads (the eraser button on the right of each item)
