### ISSUE TITLE
Failed to find io.heckel.ntfy

### ISSUE THREAD

**Issue by Integral-Tech** [NeoApplications/Neo-Store#615]
[ntfy](https://f-droid.org/packages/io.heckel.ntfy/) (io.heckel.ntfy) cannot be found in Neo Store.

![Screenshot_20240519-235044](https://github.com/NeoApplications/Neo-Store/assets/71180087/a2392039-8d67-4c88-bd92-1989f8e67bb3)

**Comment by machiav3lli** [comment]
Duplicate of #598 if you don't mind longer initial loading of the search page, you may set the value to 0.
