### ISSUE TITLE
[Feature Request] Add confirmation to uninstall button

### ISSUE THREAD

**Issue by thatso** [NeoApplications/Neo-Store#626]
**Is your feature request related to a problem? Please describe.**
I've just uninstalled an app without further confirmation by accidentally touching the `uninstall` button in the details:
![image](https://github.com/NeoApplications/Neo-Store/assets/40745263/43c781ac-5b13-485c-9a28-fe5f11dae3aa)
Luckily, I had Neo-Backup to restore it. :stuck_out_tongue: 

**Describe the solution you'd like**
Touching `uninstall` should prompt for a confirmation instead of immediately uninstalling the app.

**Describe alternatives you've considered**
At least there should be an option to chose if `uninstall` prompts for a confirmation.

**Relevant information:**
- App's Version: 1.0.2

**Comment by FBachofner** [comment]
I second this request.

I have multiple users who have accidentally deleted apps because they accidentally pressed "uninstall" (i.e. trash) instead of "share."

**Comment by machiav3lli** [comment]
This behavior should apply only to root, can you please confirm this on your side?

**Comment by thatso** [comment]
Yes, my device is rooted.

**Comment by machiav3lli** [comment]
@thatso it's not the device being rooted, rather if you're using the root installer in NS

**Comment by thatso** [comment]
@machiav3lli also yes on the root installer.

**Comment by FBachofner** [comment]
> it's not the device being rooted, rather if you're using the root installer in NS

Same for me and my various users complaining about this.
