### ISSUE TITLE
[Bug] App crashes when scrolling down all the way on newpipe

### ISSUE THREAD

**Issue by Incog5** [NeoApplications/Neo-Store#627]
**Describe the bug**
App crash

**To Reproduce**
1. Search for newpipe
2. Click on it and scroll all the way down to the releases
3. If it didn't crash yet, scroll down more

**Expected behavior**
Not to crash

Neostore 1.0.2
Crashes on phone and reproduced crash on emulator as well

**Comment by machiav3lli** [comment]
It was already reported in the community and is fixed locally, but gotta find time to finish the commits and push.

Note: Will update the commit to close this issue when pushed.

**Comment by machiav3lli** [comment]
Actually https://github.com/NeoApplications/Neo-Store/commit/c8768f31a6ae55c1d0a9ebc8c9f6320e4dc7444c fixes this and not the other mentioned issue.
