### ISSUE TITLE
[Bug] Android TV / FireTV Android 7.x problem with battery optimization since 1.0.0

### ISSUE THREAD

**Issue by Catfriend1** [NeoApplications/Neo-Store#629]
**Describe the bug**
I cannot use the Dpad to select "ignore" when the message referring to exempt from battery optimization pops up. (Previous versions of neo store worked fine on my FireTV stick because that message never came up on app start.)

Result: I can not open / use NeoStore anymore on TV since upgrading to 1.0.0.

**To Reproduce**

1. Start app v1.0.0
2. You cannot click "ignore" and the firetv platform does not offer the api for the app to exempt it from battery optimization. So hitting OK opens up the popop dialog with the button "disable" and hitting that does just nothing because the OS does not support it.

**Expected behavior**
Do not ask for battery optimization exemption on Android TV platforms. They don't support it.

**Screenshots**
If required I can use my phone to make a photo of it.

**Relevant information:**

- Device: FireTV 4K 
- Android Version: 7.x
- ROM: Amazon Stock Rom
- App's Version: 1.0.0
- Disabled battery optimization for Neo Store? Unable to do it
- What is your selected installer? Neo Store or ADB over Wireless

-----------------------------

**Comment by Catfriend1** [comment]
I've already had the same problem with my app Syncthing-Fork as it requests the user to do the battery optimization exemption mandatory during the welcome slides of the app. Here's a way I've used to detect TV's and not asking for the exemption on those devices when a TV platform is detected:

https://github.com/Catfriend1/syncthing-android/blob/b847083762d75ff14f07c067898acdad271355b0/app/src/main/java/com/nutomic/syncthingandroid/util/Util.java#L436

**Comment by Catfriend1** [comment]
I've tried to downgrade and noticed, it was already broken since 1.0.0.

**Comment by Catfriend1** [comment]
[com.machiav3lli.fdroid_914_ok.zip](https://github.com/user-attachments/files/15914868/com.machiav3lli.fdroid_914_ok.zip)
temporary workaround: Use F-Droid build 914 (from 2022)
In this version, I can properly dismiss the battery optimization screen. Agree is not possible.

**Comment by ghost** [comment]
please delete issue
