### ISSUE TITLE
Search results hidden and disappear at scrolling.

### ISSUE THREAD

**Issue by rafnov** [NeoApplications/Neo-Store#631]
When you search certain app, its result is hidden at the top window, visible only on scrolling down and disappears immediatelly after untouching screen. Very annoying.
What to do to make results on the screen after releasing touch?

**Comment by machiav3lli** [comment]
Can you please provide a screen record of this as I'm not sure I understood. Thanks

**Comment by rafnov** [comment]
I hope it can be explained by short video here:
https://youtube.com/shorts/3gfjPoI1_l8?si=Y6NFlaB0E-iRxnxn

**Comment by rafnov** [comment]
...and another one:
https://youtube.com/shorts/IgITTuQtcaE?si=-_PbOa3R1gRP8PIf

**Comment by machiav3lli** [comment]
It seems the sheet is shooting over the top of your display, so it would help maybe to get to know all the information you ignored when creating the issue (Device, Android version, ROM)

**Comment by rafnov** [comment]
> (Device, Android version, ROM)

Sure. Realme 7 Pro, Android 12, RUI 3![Screenshot_2024-06-26-07-00-30-10_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/NeoApplications/Neo-Store/assets/163686418/9cc0f27a-796e-4981-92ed-8e6f5d73dae1)

**Comment by machiav3lli** [comment]
With the search page integrated in 1.0.4, this is obsolete.
