### ISSUE TITLE
[Feature Request] New apps list vertical sort

### ISSUE THREAD

**Issue by jujubeja** [NeoApplications/Neo-Store#638]
**Is your feature request related to a problem? Please describe.**
New apps Swiping left and right wastes time, and damages the glass of your phone's screen.
**Describe the solution you'd like**
* New apps list vertical sort.
> Above Recent Updates, new apps list is vertically sorted
**Relevant information:**

----
----
---
- Device:pixel7
- Android Version:14
- ROM: (GrapheneOS)
- App's Version:1.0.3
- Disabled battery optimization for Neo Store?
- What is your selected installer?

-----------------------------

**Comment by machiav3lli** [comment]
Otherwise please avoid non-sense: `damages the glass of your phone's screen`
