### ISSUE TITLE
[Feature Request] information 404 if no results found

### ISSUE THREAD

**Issue by KMohZaid** [NeoApplications/Neo-Store#647]
When no app found, it should display 404 not found. I thought it taking time for loading but actually nothing found

**Comment by Puazroock** [comment]
Defectos en El disp

**Comment by mitulagr2** [comment]
I'll take this up

**Comment by machiav3lli** [comment]
@mitulagr2 Cool, feel free to write me if you have any questions or so.

**Comment by machiav3lli** [comment]
Covered in #670

**Comment by KMohZaid** [comment]
Arigato 🙂
