### ISSUE TITLE
[Feature Request] Feedback for search

### ISSUE THREAD

**Issue by danielwerg** [NeoApplications/Neo-Store#650]
**Is your feature request related to a problem? Please describe.**

When searching for apps and no results are found no feedback is disabled, just a blank page that could be confused for loading state.

**Describe the solution you'd like**

Display "Searching..." and "No apps found..." when appropriate.

**Describe alternatives you've considered**

Wait a couple seconds and assume no apps are found.

**Relevant information:**

- App's Version: 1.0.5

**Comment by machiav3lli** [comment]
Duplicate #647
