### ISSUE TITLE
[Feature Request] Support arm64-v7a from IzzyOnDroid repo

### ISSUE THREAD

**Issue by hololeap** [NeoApplications/Neo-Store#663]
**Is your feature request related to a problem? Please describe.**

I cannot install or update [YTDLnis](https://apt.izzysoft.de/fdroid/index/apk/com.deniscerri.ytdl) since it only shows one release (for arm64-v8a). I was, however, able to install/update this app through the [IzzyOnDroid app](https://f-droid.org/en/packages/in.sunilpaulmathew.izzyondroid/), which has a arm64-v7a release available.

**Describe the solution you'd like**

There should be more ABIs available in the releases on Neo Store, if they are available from IzzyOnDroid.

**Describe alternatives you've considered**

- Download from the IzzyOnDroid app
- Download directly from the [YTDLnis github repository](https://github.com/deniscerri/ytdlnis)

**Relevant information:**

- Device: moto g pure (XT2163-4) (arm64-v7a)
- Android Version: 12
- App's Version: Neo Store 1.0.5

**Comment by hololeap** [comment]
It looks like I may be mistaken: after trying to update the YTDLnis app using the IzzyOnDroid app, it says "application is incompatible with this device." So, this seems to be an issue with the IzzyOnDroid repo not hosting arm64-v7a versions of the YTDLnis app.

**Comment by machiav3lli** [comment]
IzzyOnDroid usually only take one apk if multiple APKs are available in the release. In the past arm7 was preferred but as far am concerned armv8 is the preference for now. It's nothing that can be "fixed" in NS. Sorry!

**Comment by hololeap** [comment]
Thanks for the reply. [Obtainium](https://github.com/ImranR98/Obtainium) seems to work nicely to fill in the gaps for apps that don't have an `arm64-v7a` APK on IzzyOnDroid.
