### ISSUE TITLE
[Bug] Bromite repository is no longer safe

### ISSUE THREAD

**Issue by yoshimo** [NeoApplications/Neo-Store#667]
**Describe the bug**
Bromite is not maintained and the domain hasn't been renewed

https://www.reddit.com/r/browsers/comments/1ft5c73/psa_expiration_of_bromiteorg/
https://github.com/bromite/bromite/issues/2610

**Expected behavior**
Remove it from the Neo-Store repository list to keep users safe.
There is cromite as a maintained fork.

**Comment by machiav3lli** [comment]
Removed in 7a52579259c3a587d8a58bb53b304dc59ce70123
