### ISSUE TITLE
[Feature Request] Add Shavian in Weblate | 𐑨𐑛 ·𐑖𐑱𐑝𐑾𐑯 𐑦𐑯 ·𐑢𐑧𐑚𐑤𐑱𐑑

### ISSUE THREAD

**Issue by JackknifedJuggernaut** [NeoApplications/Neo-Store#671]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/NeoApplications/Neo-Store/issues) and [closed](https://github.com/NeoApplications/Neo-Store/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I'm on the latest version.
- [X] I'm not using a test build (alpha/beta/release-candidate).
- [X] This issue contains only one feature request.

### Problem Description

It's related to localization. I would like to translate the project to Shavian.

𐑦𐑑'𐑕 𐑮𐑦𐑤𐑱𐑑𐑩𐑛 𐑑 𐑤𐑴𐑒𐑩𐑤𐑲𐑟𐑱𐑖𐑩𐑯. 𐑲 𐑢𐑫𐑛 𐑤𐑲𐑒 𐑑 𐑑𐑮𐑨𐑯𐑟𐑤𐑱𐑑 𐑞 𐑐𐑮𐑪𐑡𐑧𐑒𐑑 𐑑 ·𐑖𐑱𐑝𐑾𐑯.

### Proposed Solution

Add Shavian-script version of English – the “[en_Shaw](https://hosted.weblate.org/languages/en_Shaw)” locale, specifically – in Weblate; I can't do that myself.

𐑨𐑛 ·𐑖𐑱𐑝𐑾𐑯-𐑕𐑒𐑮𐑦𐑐𐑑 𐑝𐑻𐑠𐑩𐑯 𐑝 ·𐑦𐑙𐑜𐑤𐑦𐑖 – 𐑞 «[en_Shaw](https://hosted.weblate.org/languages/en_Shaw)» 𐑤𐑴𐑒𐑭𐑤, 𐑕𐑐𐑩𐑕𐑦𐑓𐑦𐑒𐑤𐑦 – 𐑦𐑯 ·𐑢𐑧𐑚𐑤𐑱𐑑; 𐑲 𐑒𐑭𐑯'𐑑 𐑛𐑵 𐑞𐑨𐑑 𐑥𐑲𐑕𐑧𐑤𐑓.

**Comment by machiav3lli** [comment]
Added. Please notify me if you'd be translating the other Neo projects to Shavian too.
