### ISSUE TITLE
Repositories sort order

### ISSUE THREAD

**Issue by mahdi1234** [NeoApplications/Neo-Store#7]
With 0.2 - I'm not sure exactly how repos are sorted, it would make more sense to me if it was simply alphabetical.

![repo_sort_order](https://user-images.githubusercontent.com/1097047/136225170-e3588c86-63e8-40fe-80d6-8b40f6d54e46.jpg)

**Comment by Elbullazul** [comment]
It's sorted by most recently added. Alphabetical order would be nice indeed
