### ISSUE TITLE
[Feature request] QR code reader for adding repositories

### ISSUE THREAD

**Issue by EdoSecco** [NeoApplications/Neo-Store#97]
Perhaps it could be something not so easy to add, but it would be very useful if we have the possibility to scan a QR code in order to add a repository.

**Comment by Iamlooker** [comment]
Is there any other app that supports this?

I like the idea, but dont expect a fast implementation, might take a long time because we have other plans

**Comment by EdoSecco** [comment]
> 
> 
> Is there any other app that supports this?

It seems no, even the official F-Droid app lacks this.

**Comment by rex07** [comment]
> Is there any other app that supports this?

I think aurora droid has this future[https://gitlab.com/AuroraOSS/auroradroid](url)

**Comment by trunc88** [comment]
F-Droid Classic supports QR codes for repositories as well
https://git.bubu1.eu/Bubu/fdroidclassic

**Comment by strider72** [comment]
Aurora Droid does this

**Comment by cmonty14** [comment]
Any progress on this feature request?

**Comment by machiav3lli** [comment]
Already added since couple of versions. To be able to use it, you have to have [BinaryEye](https://f-droid.org/de/packages/de.markusfisch.android.binaryeye/) installed
